// <auto-generated>
// Generated by OldWorldCodeGen at 2026-01-30T22:58:09.8518680Z
// Do not edit manually - regenerate with: dotnet run --project tools/OldWorldCodeGen
// </auto-generated>

using System;
using System.Collections.Generic;
using TenCrowns.GameCore;

namespace OldWorldAPIEndpoint
{
    public static partial class DataBuilders
    {
        /// <summary>
        /// Safely add a property to the data dictionary, catching any exceptions.
        /// </summary>
        private static void TryAdd(Dictionary<string, object> data, string key, Func<object> getValue)
        {
            try { data[key] = getValue(); }
            catch { /* Skip properties that throw */ }
        }

        #region Character Builder

        /// <summary>
        /// Build a Character object for JSON serialization.
        /// Auto-generated from Character.cs - 180 properties.
        /// Each property access is wrapped in try-catch for null safety.
        /// </summary>
        public static object BuildCharacterObjectGenerated(Character entity, Game game, Infos infos)
        {
            var data = new Dictionary<string, object>();

            TryAdd(data, "abdicateTurn", () => entity.getAbdicateTurn());
            TryAdd(data, "age", () => entity.getAge());
            TryAdd(data, "ageGroup", () => entity.getAgeGroup().ToString());
            TryAdd(data, "ageRemainder", () => entity.getAgeRemainder());
            TryAdd(data, "archetype", () => infos.trait(entity.getArchetype())?.mzType);
            TryAdd(data, "birthCityID", () => entity.getBirthCityID());
            TryAdd(data, "birthFatherID", () => entity.getBirthFatherID());
            TryAdd(data, "birthMotherID", () => entity.getBirthMotherID());
            TryAdd(data, "birthTurn", () => entity.getBirthTurn());
            TryAdd(data, "character", () => entity.getCharacter().ToString());
            TryAdd(data, "characterPortrait", () => entity.getCharacterPortrait().ToString());
            TryAdd(data, "cityAgentID", () => entity.getCityAgentID());
            TryAdd(data, "cityGovernorID", () => entity.getCityGovernorID());
            TryAdd(data, "clergyType", () => infos.trait(entity.getClergyType())?.mzType);
            TryAdd(data, "cognomen", () => infos.cognomen(entity.getCognomen())?.mzType);
            TryAdd(data, "council", () => infos.council(entity.getCouncil())?.mzType);
            TryAdd(data, "courtier", () => entity.getCourtier().ToString());
            TryAdd(data, "customName", () => entity.getCustomName());
            TryAdd(data, "deadCouncil", () => infos.council(entity.getDeadCouncil())?.mzType);
            TryAdd(data, "deathReason", () => entity.getDeathReason().ToString());
            TryAdd(data, "deathTurn", () => entity.getDeathTurn());
            TryAdd(data, "family", () => infos.family(entity.getFamily())?.mzType);
            TryAdd(data, "familyClass", () => entity.getFamilyClass().ToString());
            TryAdd(data, "fatherID", () => entity.getFatherID());
            TryAdd(data, "firstName", () => entity.getFirstName());
            TryAdd(data, "gender", () => entity.getGender().ToString());
            TryAdd(data, "genderInt", () => entity.getGenderInt());
            TryAdd(data, "genderOpposite", () => entity.getGenderOpposite().ToString());
            TryAdd(data, "hasArchetype", () => entity.hasArchetype());
            TryAdd(data, "hasBirthCity", () => entity.hasBirthCity());
            TryAdd(data, "hasBirthFather", () => entity.hasBirthFather());
            TryAdd(data, "hasBirthMother", () => entity.hasBirthMother());
            TryAdd(data, "hasCharacter", () => entity.hasCharacter());
            TryAdd(data, "hasCognomen", () => entity.hasCognomen());
            TryAdd(data, "hasCustomName", () => entity.hasCustomName());
            TryAdd(data, "hasDeadCouncil", () => entity.hasDeadCouncil());
            TryAdd(data, "hasExplorerAll", () => entity.hasExplorerAll());
            TryAdd(data, "hasExplorerPrereq", () => entity.hasExplorerPrereq());
            TryAdd(data, "hasFamily", () => entity.hasFamily());
            TryAdd(data, "hasFather", () => entity.hasFather());
            TryAdd(data, "hasGeneralAll", () => entity.hasGeneralAll());
            TryAdd(data, "hasGeneralPrereq", () => entity.hasGeneralPrereq());
            TryAdd(data, "hasGovernorAll", () => entity.hasGovernorAll());
            TryAdd(data, "hasGovernorPrereq", () => entity.hasGovernorPrereq());
            TryAdd(data, "hasItems", () => entity.hasItems());
            TryAdd(data, "hasMother", () => entity.hasMother());
            TryAdd(data, "hasName", () => entity.hasName());
            TryAdd(data, "hasNation", () => entity.hasNation());
            TryAdd(data, "hasNickname", () => entity.hasNickname());
            TryAdd(data, "hasPlayer", () => entity.hasPlayer());
            TryAdd(data, "hasReligion", () => entity.hasReligion());
            TryAdd(data, "hasSpouseAlive", () => entity.hasSpouseAlive());
            TryAdd(data, "hasSpouseForeign", () => entity.hasSpouseForeign());
            TryAdd(data, "hasSpouseTribe", () => entity.hasSpouseTribe());
            TryAdd(data, "hasTitle", () => entity.hasTitle());
            TryAdd(data, "hasTraitDieProb", () => entity.hasTraitDieProb());
            TryAdd(data, "hasTraitDoomed", () => entity.hasTraitDoomed());
            TryAdd(data, "hasTraitFormerRegent", () => entity.hasTraitFormerRegent());
            TryAdd(data, "hasTraitNoBirth", () => entity.hasTraitNoBirth());
            TryAdd(data, "hasTraitNoCouncil", () => entity.hasTraitNoCouncil());
            TryAdd(data, "hasTraitNoCourtier", () => entity.hasTraitNoCourtier());
            TryAdd(data, "hasTraitNoEvents", () => entity.hasTraitNoEvents());
            TryAdd(data, "hasTraitNoExplorer", () => entity.hasTraitNoExplorer());
            TryAdd(data, "hasTraitNoFamilyHead", () => entity.hasTraitNoFamilyHead());
            TryAdd(data, "hasTraitNoGeneral", () => entity.hasTraitNoGeneral());
            TryAdd(data, "hasTraitNoGovernor", () => entity.hasTraitNoGovernor());
            TryAdd(data, "hasTraitNoJob", () => entity.hasTraitNoJob());
            TryAdd(data, "hasTraitNoMarry", () => entity.hasTraitNoMarry());
            TryAdd(data, "hasTraitNoReligion", () => entity.hasTraitNoReligion());
            TryAdd(data, "hasTraitNoReligionHeadNew", () => entity.hasTraitNoReligionHeadNew());
            TryAdd(data, "hasTraitNoSuccession", () => entity.hasTraitNoSuccession());
            TryAdd(data, "hasTraitRegent", () => entity.hasTraitRegent());
            TryAdd(data, "hasTraitSuccessionBypass", () => entity.hasTraitSuccessionBypass());
            TryAdd(data, "hasTraitSuccessionReturn", () => entity.hasTraitSuccessionReturn());
            TryAdd(data, "hasUnit", () => entity.hasUnit());
            TryAdd(data, "headReligion", () => infos.religion(entity.getHeadReligion())?.mzType);
            TryAdd(data, "id", () => entity.getID());
            TryAdd(data, "isAbdicated", () => entity.isAbdicated());
            TryAdd(data, "isActivePlayer", () => entity.isActivePlayer());
            TryAdd(data, "isAdult", () => entity.isAdult());
            TryAdd(data, "isAgeless", () => entity.isAgeless());
            TryAdd(data, "isAlive", () => entity.isAlive());
            TryAdd(data, "isAnyDirty", () => entity.isAnyDirty());
            TryAdd(data, "isAttractedToAny", () => entity.isAttractedToAny());
            TryAdd(data, "isBisexual", () => entity.isBisexual());
            TryAdd(data, "isCityAgent", () => entity.isCityAgent());
            TryAdd(data, "isCityGovernor", () => entity.isCityGovernor());
            TryAdd(data, "isClergy", () => entity.isClergy());
            TryAdd(data, "isCouncil", () => entity.isCouncil());
            TryAdd(data, "isCourtier", () => entity.isCourtier());
            TryAdd(data, "isDead", () => entity.isDead());
            TryAdd(data, "isFamilyHead", () => entity.isFamilyHead());
            TryAdd(data, "isFamilyHeadSpouse", () => entity.isFamilyHeadSpouse());
            TryAdd(data, "isFemale", () => entity.isFemale());
            TryAdd(data, "isFertileAge", () => entity.isFertileAge());
            TryAdd(data, "isForceInheritanceTreeInclude", () => entity.isForceInheritanceTreeInclude());
            TryAdd(data, "isGay", () => entity.isGay());
            TryAdd(data, "isHeir", () => entity.isHeir());
            TryAdd(data, "isHeirSpouse", () => entity.isHeirSpouse());
            TryAdd(data, "isHuman", () => entity.isHuman());
            TryAdd(data, "isInfertile", () => entity.isInfertile());
            TryAdd(data, "isJob", () => entity.isJob());
            TryAdd(data, "isLeader", () => entity.isLeader());
            TryAdd(data, "isLeaderAncestor", () => entity.isLeaderAncestor());
            TryAdd(data, "isLeaderAnySibling", () => entity.isLeaderAnySibling());
            TryAdd(data, "isLeaderChild", () => entity.isLeaderChild());
            TryAdd(data, "isLeaderDescendant", () => entity.isLeaderDescendant());
            TryAdd(data, "isLeaderOrChildOfLeader", () => entity.isLeaderOrChildOfLeader());
            TryAdd(data, "isLeaderOrDescendant", () => entity.isLeaderOrDescendant());
            TryAdd(data, "isLeaderOrHeir", () => entity.isLeaderOrHeir());
            TryAdd(data, "isLeaderOrSpouse", () => entity.isLeaderOrSpouse());
            TryAdd(data, "isLeaderOrSpouseOrHeir", () => entity.isLeaderOrSpouseOrHeir());
            TryAdd(data, "isLeaderOrSpouseOrSuccessor", () => entity.isLeaderOrSpouseOrSuccessor());
            TryAdd(data, "isLeaderOrSuccessor", () => entity.isLeaderOrSuccessor());
            TryAdd(data, "isLeaderSpouse", () => entity.isLeaderSpouse());
            TryAdd(data, "isMale", () => entity.isMale());
            TryAdd(data, "isOrWasLeader", () => entity.isOrWasLeader());
            TryAdd(data, "isOrWasLeaderSpouse", () => entity.isOrWasLeaderSpouse());
            TryAdd(data, "isOrWasRegent", () => entity.isOrWasRegent());
            TryAdd(data, "isRegent", () => entity.isRegent());
            TryAdd(data, "isReligionHead", () => entity.isReligionHead());
            TryAdd(data, "isRetired", () => entity.isRetired());
            TryAdd(data, "isRoyal", () => entity.isRoyal());
            TryAdd(data, "isRoyalSpouse", () => entity.isRoyalSpouse());
            TryAdd(data, "isSafe", () => entity.isSafe());
            TryAdd(data, "isSpouseLeaderDescendant", () => entity.isSpouseLeaderDescendant());
            TryAdd(data, "isSuccessionSkipRegent", () => entity.isSuccessionSkipRegent());
            TryAdd(data, "isSuccessor", () => entity.isSuccessor());
            TryAdd(data, "isSuccessorParent", () => entity.isSuccessorParent());
            TryAdd(data, "isSuccessorSpouse", () => entity.isSuccessorSpouse());
            TryAdd(data, "isTemporary", () => entity.isTemporary());
            TryAdd(data, "isTribe", () => entity.isTribe());
            TryAdd(data, "isTribeLeader", () => entity.isTribeLeader());
            TryAdd(data, "isUnitExplorer", () => entity.isUnitExplorer());
            TryAdd(data, "isUnitGeneral", () => entity.isUnitGeneral());
            TryAdd(data, "isValidChooseName", () => entity.isValidChooseName());
            TryAdd(data, "job", () => infos.job(entity.getJob())?.mzType);
            TryAdd(data, "leaderIndex", () => entity.getLeaderIndex());
            TryAdd(data, "leaderTurn", () => entity.getLeaderTurn());
            TryAdd(data, "legitimacy", () => entity.getLegitimacy());
            TryAdd(data, "level", () => entity.getLevel());
            TryAdd(data, "makeAgentExtraOpinion", () => entity.getMakeAgentExtraOpinion());
            TryAdd(data, "makeExplorerExtraOpinion", () => entity.getMakeExplorerExtraOpinion());
            TryAdd(data, "makeGeneralExtraOpinion", () => entity.getMakeGeneralExtraOpinion());
            TryAdd(data, "makeGovernorExtraOpinion", () => entity.getMakeGovernorExtraOpinion());
            TryAdd(data, "maxStrengths", () => entity.getMaxStrengths());
            TryAdd(data, "maxWeaknesses", () => entity.getMaxWeaknesses());
            TryAdd(data, "motherID", () => entity.getMotherID());
            TryAdd(data, "nameType", () => entity.getNameType().ToString());
            TryAdd(data, "nation", () => infos.nation(entity.getNation())?.mzType);
            TryAdd(data, "nationTurn", () => entity.getNationTurn());
            TryAdd(data, "nickname", () => entity.getNickname().ToString());
            TryAdd(data, "nicknameText", () => entity.getNicknameText());
            TryAdd(data, "numChildren", () => entity.getNumChildren());
            TryAdd(data, "numEventStoryTexts", () => entity.getNumEventStoryTexts());
            TryAdd(data, "numEventStoryTurns", () => entity.getNumEventStoryTurns());
            TryAdd(data, "numSpouses", () => entity.getNumSpouses());
            TryAdd(data, "player", () => entity.getPlayer().ToString());
            TryAdd(data, "playerInt", () => entity.getPlayerInt());
            TryAdd(data, "playerOpinionOfCharacterReligion", () => entity.getPlayerOpinionOfCharacterReligion().ToString());
            TryAdd(data, "ratingAttackModifierTotal", () => entity.getRatingAttackModifierTotal());
            TryAdd(data, "ratingCriticalChanceTotal", () => entity.getRatingCriticalChanceTotal());
            TryAdd(data, "ratingHarvestModifierTotal", () => entity.getRatingHarvestModifierTotal());
            TryAdd(data, "ratingUnitXPTotal", () => entity.getRatingUnitXPTotal());
            TryAdd(data, "regentTurn", () => entity.getRegentTurn());
            TryAdd(data, "religion", () => infos.religion(entity.getReligion())?.mzType);
            TryAdd(data, "safeTurn", () => entity.getSafeTurn());
            TryAdd(data, "suffix", () => entity.getSuffix());
            TryAdd(data, "team", () => entity.getTeam().ToString());
            TryAdd(data, "title", () => entity.getTitle().ToString());
            TryAdd(data, "traitBirthModifier", () => entity.getTraitBirthModifier());
            TryAdd(data, "traitNickname", () => entity.getTraitNickname().ToString());
            TryAdd(data, "traitTitle", () => entity.getTraitTitle().ToString());
            TryAdd(data, "tribe", () => infos.tribe(entity.getTribe())?.mzType);
            TryAdd(data, "unitBuildModifier", () => entity.getUnitBuildModifier());
            TryAdd(data, "unitID", () => entity.getUnitID());
            TryAdd(data, "upgradeXPThreshold", () => entity.getUpgradeXPThreshold());
            TryAdd(data, "wasFamilyHead", () => infos.family(entity.getWasFamilyHead())?.mzType);
            TryAdd(data, "wasReligionHead", () => infos.religion(entity.getWasReligionHead())?.mzType);
            TryAdd(data, "xp", () => entity.getXP());

            return data;
        }

        // Parameterized getters not included in basic builder:
        // - getAgeGroupOnTurn(1 params) -> CharacterAgeGroupType
        // - getAgeOnTurn(1 params) -> int
        // - getAncestorLevel(2 params) -> int
        // - getChangeJobExtraOpinion(1 params) -> int
        // - getCharacterRelation(1 params) -> RelativeType
        // - getCognomenMinValue(1 params) -> int
        // - getEventStoryText(1 params) -> CharacterStoryData
        // - getEventStoryTurn(1 params) -> int
        // - getFamilyOpinionCouncil(1 params) -> int
        // - getFirstName(1 params) -> StringBuilder
        // - getFullName(11 params) -> string
        // - getFullName(12 params) -> StringBuilder
        // - getFullNameExtraVariable(6 params) -> TextVariable
        // - getFullNameVariable(12 params) -> TextVariable
        // - getJobOpinion(1 params) -> int
        // - getLegitimacy(2 params) -> int
        // - getMakeCouncilExtraOpinion(1 params) -> int
        // - getNameVariable(7 params) -> TextVariable
        // - getNationEthnicity(1 params) -> int
        // - getOpinion(1 params) -> OpinionCharacterType
        // ... and 67 more

        #endregion

        #region City Builder

        /// <summary>
        /// Build a City object for JSON serialization.
        /// Auto-generated from City.cs - 123 properties.
        /// Each property access is wrapped in try-catch for null safety.
        /// </summary>
        public static object BuildCityObjectGenerated(City entity, Game game, Infos infos)
        {
            var data = new Dictionary<string, object>();

            TryAdd(data, "activeImprovementClassCountAll", () => entity.getActiveImprovementClassCountAll());
            TryAdd(data, "activeImprovementCountAll", () => entity.getActiveImprovementCountAll());
            TryAdd(data, "adjacentClassCostModifier", () => entity.getAdjacentClassCostModifier());
            TryAdd(data, "assimilateTurns", () => entity.getAssimilateTurns());
            TryAdd(data, "buildCount", () => entity.getBuildCount());
            TryAdd(data, "buildTurnChange", () => entity.getBuildTurnChange());
            TryAdd(data, "buildUnitFamily", () => infos.family(entity.getBuildUnitFamily())?.mzType);
            TryAdd(data, "buyTileCount", () => entity.getBuyTileCount());
            TryAdd(data, "capturePlayer", () => entity.getCapturePlayer().ToString());
            TryAdd(data, "captureTeam", () => entity.getCaptureTeam().ToString());
            TryAdd(data, "captureThreshold", () => entity.getCaptureThreshold());
            TryAdd(data, "captureTribe", () => infos.tribe(entity.getCaptureTribe())?.mzType);
            TryAdd(data, "captureTurns", () => entity.getCaptureTurns());
            TryAdd(data, "citizens", () => entity.getCitizens());
            TryAdd(data, "citizensPlusQueuedWithNoProgress", () => entity.getCitizensPlusQueuedWithNoProgress());
            TryAdd(data, "citizensQueue", () => entity.getCitizensQueue());
            TryAdd(data, "citizensTotal", () => entity.getCitizensTotal());
            TryAdd(data, "culture", () => infos.culture(entity.getCulture())?.mzType);
            TryAdd(data, "cultureStep", () => entity.getCultureStep());
            TryAdd(data, "currentBuildType", () => entity.getCurrentBuildType().ToString());
            TryAdd(data, "damage", () => entity.getDamage());
            TryAdd(data, "defaultGovernorID", () => entity.getDefaultGovernorID());
            TryAdd(data, "family", () => infos.family(entity.getFamily())?.mzType);
            TryAdd(data, "familyClass", () => entity.getFamilyClass().ToString());
            TryAdd(data, "familyOpinion", () => entity.getFamilyOpinion().ToString());
            TryAdd(data, "firstPlayer", () => entity.getFirstPlayer().ToString());
            TryAdd(data, "firstTeam", () => entity.getFirstTeam().ToString());
            TryAdd(data, "foundedTurn", () => entity.getFoundedTurn());
            TryAdd(data, "giftedTurn", () => entity.getGiftedTurn());
            TryAdd(data, "governorID", () => entity.getGovernorID());
            TryAdd(data, "grammaticalGender", () => entity.getGrammaticalGender().ToString());
            TryAdd(data, "growthCount", () => entity.getGrowthCount());
            TryAdd(data, "happinessLevel", () => entity.getHappinessLevel());
            TryAdd(data, "hasAnyAgentCharacter", () => entity.hasAnyAgentCharacter());
            TryAdd(data, "hasAutobuildQueued", () => entity.hasAutobuildQueued());
            TryAdd(data, "hasBuild", () => entity.hasBuild());
            TryAdd(data, "hasBuildAnyReligionUnitUnlock", () => entity.hasBuildAnyReligionUnitUnlock());
            TryAdd(data, "hasBuildPlanned", () => entity.hasBuildPlanned());
            TryAdd(data, "hasCapturePlayer", () => entity.hasCapturePlayer());
            TryAdd(data, "hasCaptureTribe", () => entity.hasCaptureTribe());
            TryAdd(data, "hasCompletedBuild", () => entity.hasCompletedBuild());
            TryAdd(data, "hasDefaultGovernor", () => entity.hasDefaultGovernor());
            TryAdd(data, "hasFamily", () => entity.hasFamily());
            TryAdd(data, "hasFamilyOpinion", () => entity.hasFamilyOpinion());
            TryAdd(data, "hasGovernor", () => entity.hasGovernor());
            TryAdd(data, "hasLastPlayer", () => entity.hasLastPlayer());
            TryAdd(data, "hasLastTribe", () => entity.hasLastTribe());
            TryAdd(data, "hasNation", () => entity.hasNation());
            TryAdd(data, "hasPlayer", () => entity.hasPlayer());
            TryAdd(data, "hasRebelEffects", () => entity.hasRebelEffects());
            TryAdd(data, "hasStateReligion", () => entity.hasStateReligion());
            TryAdd(data, "healExtra", () => entity.getHealExtra());
            TryAdd(data, "hp", () => entity.getHP());
            TryAdd(data, "hpMax", () => entity.getHPMax());
            TryAdd(data, "hpMaxExtra", () => entity.getHPMaxExtra());
            TryAdd(data, "hurryCivicsCost", () => entity.getHurryCivicsCost());
            TryAdd(data, "hurryCivicsCount", () => entity.getHurryCivicsCount());
            TryAdd(data, "hurryDiscontent", () => entity.getHurryDiscontent());
            TryAdd(data, "hurryDiscontentModifier", () => entity.getHurryDiscontentModifier());
            TryAdd(data, "hurryMoneyCost", () => entity.getHurryMoneyCost());
            TryAdd(data, "hurryMoneyCount", () => entity.getHurryMoneyCount());
            TryAdd(data, "hurryOrdersCost", () => entity.getHurryOrdersCost());
            TryAdd(data, "hurryOrdersCount", () => entity.getHurryOrdersCount());
            TryAdd(data, "hurryPopulationCost", () => entity.getHurryPopulationCost());
            TryAdd(data, "hurryPopulationCount", () => entity.getHurryPopulationCount());
            TryAdd(data, "hurryTrainingCost", () => entity.getHurryTrainingCost());
            TryAdd(data, "hurryTrainingCount", () => entity.getHurryTrainingCount());
            TryAdd(data, "id", () => entity.getID());
            TryAdd(data, "improvementCostModifier", () => entity.getImprovementCostModifier());
            TryAdd(data, "isActivePlayer", () => entity.isActivePlayer());
            TryAdd(data, "isAnyDirty", () => entity.isAnyDirty());
            TryAdd(data, "isAutomated", () => entity.isAutomated());
            TryAdd(data, "isBuildNoHurry", () => entity.isBuildNoHurry());
            TryAdd(data, "isCapital", () => entity.isCapital());
            TryAdd(data, "isCapturedCapital", () => entity.isCapturedCapital());
            TryAdd(data, "isConnected", () => entity.isConnected());
            TryAdd(data, "isDamaged", () => entity.isDamaged());
            TryAdd(data, "isDefaultGovernorRuling", () => entity.isDefaultGovernorRuling());
            TryAdd(data, "isFamilySeat", () => entity.isFamilySeat());
            TryAdd(data, "isGoverned", () => entity.isGoverned());
            TryAdd(data, "isGovernorLeader", () => entity.isGovernorLeader());
            TryAdd(data, "isHuman", () => entity.isHuman());
            TryAdd(data, "isIdle", () => entity.isIdle());
            TryAdd(data, "isReligionHolyCityAny", () => entity.isReligionHolyCityAny());
            TryAdd(data, "isTribe", () => entity.isTribe());
            TryAdd(data, "isUnitCapturingCity", () => entity.isUnitCapturingCity());
            TryAdd(data, "isVulnerable", () => entity.isVulnerable());
            TryAdd(data, "isYieldRateDefendingAny", () => entity.isYieldRateDefendingAny());
            TryAdd(data, "lastPlayer", () => entity.getLastPlayer().ToString());
            TryAdd(data, "lastTeam", () => entity.getLastTeam().ToString());
            TryAdd(data, "lastTribe", () => infos.tribe(entity.getLastTribe())?.mzType);
            TryAdd(data, "luxuryCount", () => entity.getLuxuryCount());
            TryAdd(data, "militaryUnitCount", () => entity.getMilitaryUnitCount());
            TryAdd(data, "name", () => entity.getName());
            TryAdd(data, "nameType", () => entity.getNameType().ToString());
            TryAdd(data, "nation", () => infos.nation(entity.getNation())?.mzType);
            TryAdd(data, "numRandomPromotions", () => entity.getNumRandomPromotions());
            TryAdd(data, "paganReligionCount", () => entity.getPaganReligionCount());
            TryAdd(data, "passiveHealDamage", () => entity.getPassiveHealDamage());
            TryAdd(data, "player", () => entity.getPlayer().ToString());
            TryAdd(data, "playerInt", () => entity.getPlayerInt());
            TryAdd(data, "population", () => entity.getPopulation());
            TryAdd(data, "projectCostModifier", () => entity.getProjectCostModifier());
            TryAdd(data, "raidedTurn", () => entity.getRaidedTurn());
            TryAdd(data, "rangeChange", () => entity.getRangeChange());
            TryAdd(data, "regrowthModifier", () => entity.getRegrowthModifier());
            TryAdd(data, "religionCount", () => entity.getReligionCount());
            TryAdd(data, "religionNonStateCount", () => entity.getReligionNonStateCount());
            TryAdd(data, "saltWaterTiles", () => entity.getSaltWaterTiles());
            TryAdd(data, "specialistCostModifier", () => entity.getSpecialistCostModifier());
            TryAdd(data, "specialistCount", () => entity.getSpecialistCount());
            TryAdd(data, "specialistProducedCount", () => entity.getSpecialistProducedCount());
            TryAdd(data, "specialistRuralTrainTimeModifier", () => entity.getSpecialistRuralTrainTimeModifier());
            TryAdd(data, "specialistUrbanCostModifier", () => entity.getSpecialistUrbanCostModifier());
            TryAdd(data, "specialistUrbanTrainTimeModifier", () => entity.getSpecialistUrbanTrainTimeModifier());
            TryAdd(data, "strengthModifier", () => entity.getStrengthModifier());
            TryAdd(data, "team", () => entity.getTeam().ToString());
            TryAdd(data, "tileID", () => entity.getTileID());
            TryAdd(data, "tradeNetwork", () => entity.getTradeNetwork());
            TryAdd(data, "tribe", () => infos.tribe(entity.getTribe())?.mzType);
            TryAdd(data, "urbanBuildTurnChange", () => entity.getUrbanBuildTurnChange());
            TryAdd(data, "urbanSpecialistCount", () => entity.getUrbanSpecialistCount());
            TryAdd(data, "urbanTiles", () => entity.getUrbanTiles());

            return data;
        }

        // Parameterized getters not included in basic builder:
        // - getActiveImprovementClassCount(1 params) -> int
        // - getActiveImprovementCount(1 params) -> int
        // - getAddProjectYieldRate(3 params) -> int
        // - getAddResourceTiles(3 params) -> bool
        // - getAgentCharacterID(1 params) -> int
        // - getAgentTeamPlayer(1 params) -> PlayerType
        // - getAssimilateYieldModifier(1 params) -> int
        // - getBaseYieldNet(1 params) -> int
        // - getBaseYieldNetForGovernor(3 params) -> int
        // - getBestSpecialistNoPrereq(1 params) -> SpecialistType
        // - getBorderPattern(1 params) -> BorderPatternType
        // - getBuildDiff(2 params) -> int
        // - getBuildDiffWholePositive(2 params) -> int
        // - getBuildProgress(2 params) -> int
        // - getBuildQueueNode(1 params) -> CityQueueData
        // - getBuildRate(2 params) -> int
        // - getBuildThreshold(1 params) -> int
        // - getBuildThresholdWhole(1 params) -> int
        // - getBuildTurnsLeft(1 params) -> int
        // - getBuildUnitLevels(1 params) -> int
        // ... and 124 more

        #endregion

        #region Player Builder

        /// <summary>
        /// Build a Player object for JSON serialization.
        /// Auto-generated from Player.cs - 122 properties.
        /// Each property access is wrapped in try-catch for null safety.
        /// </summary>
        public static object BuildPlayerObjectGenerated(Player entity, Game game, Infos infos)
        {
            var data = new Dictionary<string, object>();

            TryAdd(data, "aiAutoPlayToTurn", () => entity.getAIAutoPlayToTurn());
            TryAdd(data, "borderVisibility", () => entity.getBorderVisibility());
            TryAdd(data, "buyTileCount", () => entity.getBuyTileCount());
            TryAdd(data, "capitalCityID", () => entity.getCapitalCityID());
            TryAdd(data, "chosenHeirID", () => entity.getChosenHeirID());
            TryAdd(data, "consumptionModifier", () => entity.getConsumptionModifier());
            TryAdd(data, "convertOrdersCost", () => entity.getConvertOrdersCost());
            TryAdd(data, "convertOrdersYield", () => infos.yield(entity.getConvertOrdersYield())?.mzType);
            TryAdd(data, "crest", () => entity.getCrest().ToString());
            TryAdd(data, "customName", () => entity.getCustomName());
            TryAdd(data, "customReminder", () => entity.getCustomReminder());
            TryAdd(data, "development", () => entity.getDevelopment().ToString());
            TryAdd(data, "difficulty", () => entity.getDifficulty().ToString());
            TryAdd(data, "difficultyMode", () => entity.getDifficultyMode().ToString());
            TryAdd(data, "dynasty", () => entity.getDynasty().ToString());
            TryAdd(data, "familySupremacy", () => infos.family(entity.getFamilySupremacy())?.mzType);
            TryAdd(data, "firstPopup", () => entity.getFirstPopup());
            TryAdd(data, "fixedNumCities", () => entity.getFixedNumCities());
            TryAdd(data, "founderID", () => entity.getFounderID());
            TryAdd(data, "harvestModifier", () => entity.getHarvestModifier());
            TryAdd(data, "hasAchievementLocked", () => entity.hasAchievementLocked());
            TryAdd(data, "hasAchievementUnlocked", () => entity.hasAchievementUnlocked());
            TryAdd(data, "hasAutomatedUnits", () => entity.hasAutomatedUnits());
            TryAdd(data, "hasCapitalCity", () => entity.hasCapitalCity());
            TryAdd(data, "hasChosenHeir", () => entity.hasChosenHeir());
            TryAdd(data, "hasCustomName", () => entity.hasCustomName());
            TryAdd(data, "hasDecisions", () => entity.hasDecisions());
            TryAdd(data, "hasDynasty", () => entity.hasDynasty());
            TryAdd(data, "hasFounder", () => entity.hasFounder());
            TryAdd(data, "hasHeir", () => entity.hasHeir());
            TryAdd(data, "hasLeader", () => entity.hasLeader());
            TryAdd(data, "hasLeaderFamily", () => entity.hasLeaderFamily());
            TryAdd(data, "hasLeaderSpouseAlive", () => entity.hasLeaderSpouseAlive());
            TryAdd(data, "hasNation", () => entity.hasNation());
            TryAdd(data, "hasScenarioCompleted", () => entity.hasScenarioCompleted());
            TryAdd(data, "hasStateReligion", () => entity.hasStateReligion());
            TryAdd(data, "hasTurnSummary", () => entity.hasTurnSummary());
            TryAdd(data, "isActive", () => entity.isActive());
            TryAdd(data, "isAIAutoPlay", () => entity.isAIAutoPlay());
            TryAdd(data, "isAlive", () => entity.isAlive());
            TryAdd(data, "isAnyDirty", () => entity.isAnyDirty());
            TryAdd(data, "isAnyPickLater", () => entity.isAnyPickLater());
            TryAdd(data, "isAnyTechAvailable", () => entity.isAnyTechAvailable());
            TryAdd(data, "isCityMaxReached", () => entity.isCityMaxReached());
            TryAdd(data, "isCompletedGameSaved", () => entity.isCompletedGameSaved());
            TryAdd(data, "isConvertedLegitimacy", () => entity.isConvertedLegitimacy());
            TryAdd(data, "isDead", () => entity.isDead());
            TryAdd(data, "isFirstTurnProcessing", () => entity.isFirstTurnProcessing());
            TryAdd(data, "isFounded", () => entity.isFounded());
            TryAdd(data, "isHuman", () => entity.isHuman());
            TryAdd(data, "isHumanOriginal", () => entity.isHumanOriginal());
            TryAdd(data, "isInitialized", () => entity.isInitialized());
            TryAdd(data, "isLeaderAlive", () => entity.isLeaderAlive());
            TryAdd(data, "isPlaying", () => entity.isPlaying());
            TryAdd(data, "isProcessingTurn", () => entity.isProcessingTurn());
            TryAdd(data, "isProcessingTurnStart", () => entity.isProcessingTurnStart());
            TryAdd(data, "isResearching", () => entity.isResearching());
            TryAdd(data, "isStartCityNumberFlexible", () => entity.isStartCityNumberFlexible());
            TryAdd(data, "isSurrendered", () => entity.isSurrendered());
            TryAdd(data, "isTeamHuman", () => entity.isTeamHuman());
            TryAdd(data, "isTechRedraw", () => entity.isTechRedraw());
            TryAdd(data, "isTurnEnded", () => entity.isTurnEnded());
            TryAdd(data, "isTurnSummaryReady", () => entity.isTurnSummaryReady());
            TryAdd(data, "isTutorial", () => entity.isTutorial());
            TryAdd(data, "isUsedOffensive", () => entity.isUsedOffensive());
            TryAdd(data, "isVersionMismatch", () => entity.isVersionMismatch());
            TryAdd(data, "language", () => entity.getLanguage().ToString());
            TryAdd(data, "lastDoTurn", () => entity.getLastDoTurn());
            TryAdd(data, "leaderFamily", () => infos.family(entity.getLeaderFamily())?.mzType);
            TryAdd(data, "legitimacy", () => entity.getLegitimacy());
            TryAdd(data, "minStartingCities", () => entity.getMinStartingCities());
            TryAdd(data, "missionModifier", () => entity.getMissionModifier());
            TryAdd(data, "money", () => entity.getMoney());
            TryAdd(data, "moneyWhole", () => entity.getMoneyWhole());
            TryAdd(data, "nation", () => infos.nation(entity.getNation())?.mzType);
            TryAdd(data, "numCities", () => entity.getNumCities());
            TryAdd(data, "numDecisions", () => entity.getNumDecisions());
            TryAdd(data, "numEmptySites", () => entity.getNumEmptySites());
            TryAdd(data, "numFamilies", () => entity.getNumFamilies());
            TryAdd(data, "numGameLoads", () => entity.getNumGameLoads());
            TryAdd(data, "numGoals", () => entity.getNumGoals());
            TryAdd(data, "numMemories", () => entity.getNumMemories());
            TryAdd(data, "numMissions", () => entity.getNumMissions());
            TryAdd(data, "numPopups", () => entity.getNumPopups());
            TryAdd(data, "numStartingTiles", () => entity.getNumStartingTiles());
            TryAdd(data, "numTiles", () => entity.getNumTiles());
            TryAdd(data, "numTrades", () => entity.getNumTrades());
            TryAdd(data, "numTributes", () => entity.getNumTributes());
            TryAdd(data, "numUnits", () => entity.getNumUnits());
            TryAdd(data, "onlineID", () => entity.getOnlineID());
            TryAdd(data, "ordersLeft", () => entity.getOrdersLeft());
            TryAdd(data, "originalCapitalCityID", () => entity.getOriginalCapitalCityID());
            TryAdd(data, "player", () => entity.getPlayer().ToString());
            TryAdd(data, "playerEmail", () => entity.getPlayerEmail());
            TryAdd(data, "playerInt", () => entity.getPlayerInt());
            TryAdd(data, "popupTechDiscovered", () => infos.tech(entity.getPopupTechDiscovered())?.mzType);
            TryAdd(data, "recruitLegitimacy", () => entity.getRecruitLegitimacy());
            TryAdd(data, "reloads", () => entity.getReloads());
            TryAdd(data, "saltWaterTileCount", () => entity.getSaltWaterTileCount());
            TryAdd(data, "sellPenaltyModifier", () => entity.getSellPenaltyModifier());
            TryAdd(data, "startingTileID", () => entity.getStartingTileID());
            TryAdd(data, "startTurnCities", () => entity.getStartTurnCities());
            TryAdd(data, "stateReligion", () => infos.religion(entity.getStateReligion())?.mzType);
            TryAdd(data, "stateReligionChangeCount", () => entity.getStateReligionChangeCount());
            TryAdd(data, "stateReligionSpreadChange", () => entity.getStateReligionSpreadChange());
            TryAdd(data, "successionCount", () => entity.getSuccessionCount());
            TryAdd(data, "successionGender", () => entity.getSuccessionGender().ToString());
            TryAdd(data, "successionOrder", () => entity.getSuccessionOrder().ToString());
            TryAdd(data, "team", () => entity.getTeam().ToString());
            TryAdd(data, "techCostModifier", () => entity.getTechCostModifier());
            TryAdd(data, "techResearching", () => infos.tech(entity.getTechResearching())?.mzType);
            TryAdd(data, "techsAvailableChange", () => entity.getTechsAvailableChange());
            TryAdd(data, "timeStockpile", () => entity.getTimeStockpile());
            TryAdd(data, "trainingOrderModifier", () => entity.getTrainingOrderModifier());
            TryAdd(data, "tribeFatigueLimitChange", () => entity.getTribeFatigueLimitChange());
            TryAdd(data, "tribeMercenaryCount", () => entity.getTribeMercenaryCount());
            TryAdd(data, "turnTimeNeeded", () => entity.getTurnTimeNeeded());
            TryAdd(data, "visionChange", () => entity.getVisionChange());
            TryAdd(data, "wonderModifier", () => entity.getWonderModifier());
            TryAdd(data, "worldReligionCount", () => entity.getWorldReligionCount());
            TryAdd(data, "worldReligionSpreadChange", () => entity.getWorldReligionSpreadChange());
            TryAdd(data, "yieldUpkeepModifier", () => entity.getYieldUpkeepModifier());

            return data;
        }

        // Parameterized getters not included in basic builder:
        // - getActiveImprovementClassCount(1 params) -> int
        // - getActiveImprovementCount(1 params) -> int
        // - getActiveLaw(1 params) -> LawType
        // - getAddUrbanCost(2 params) -> int
        // - getAdoptReligionCost(1 params) -> int
        // - getAmbitionDecisions(1 params) -> int
        // - getBonesTime(1 params) -> int
        // - getBonusCount(1 params) -> int
        // - getBorderColor(1 params) -> ColorType
        // - getBorderPattern(1 params) -> BorderPatternType
        // - getBuyImprovementCost(4 params) -> int
        // - getBuyYieldsCost(1 params) -> int
        // - getBuyYieldsCost(1 params) -> int
        // - getCharacterMission(1 params) -> MissionData
        // - getConnectedForeignYieldPer(3 params) -> int
        // - getConnectedForeignYieldTotal(3 params) -> int
        // - getCouncilCharacter(1 params) -> int
        // - getCouncilYieldRateCharacterCity(3 params) -> int
        // - getCurrentTurnLogText(2 params) -> StringBuilder
        // - getDecisionAt(1 params) -> DecisionData
        // ... and 175 more

        #endregion

        #region Tile Builder

        /// <summary>
        /// Build a Tile object for JSON serialization.
        /// Auto-generated from Tile.cs - 115 properties.
        /// Each property access is wrapped in try-catch for null safety.
        /// </summary>
        public static object BuildTileObjectGenerated(Tile entity, Game game, Infos infos)
        {
            var data = new Dictionary<string, object>();

            TryAdd(data, "activeImprovementClass", () => entity.getActiveImprovementClass().ToString());
            TryAdd(data, "area", () => entity.getArea());
            TryAdd(data, "areaTileCount", () => entity.getAreaTileCount());
            TryAdd(data, "cityID", () => entity.getCityID());
            TryAdd(data, "citySite", () => entity.getCitySite().ToString());
            TryAdd(data, "cityTerritory", () => entity.getCityTerritory());
            TryAdd(data, "constructionProgress", () => entity.getConstructionProgress());
            TryAdd(data, "currentSpecialist", () => infos.specialist(entity.getCurrentSpecialist())?.mzType);
            TryAdd(data, "customMapElementName", () => entity.getCustomMapElementName());
            TryAdd(data, "extraBlockingVisibilityHeight", () => entity.getExtraBlockingVisibilityHeight());
            TryAdd(data, "family", () => infos.family(entity.getFamily())?.mzType);
            TryAdd(data, "harvestTurn", () => entity.getHarvestTurn());
            TryAdd(data, "hasCanDamageUnit", () => entity.hasCanDamageUnit());
            TryAdd(data, "hasCity", () => entity.hasCity());
            TryAdd(data, "hasCityTerritory", () => entity.hasCityTerritory());
            TryAdd(data, "hasFamily", () => entity.hasFamily());
            TryAdd(data, "hasFreeSpecialist", () => entity.hasFreeSpecialist());
            TryAdd(data, "hasGovernor", () => entity.hasGovernor());
            TryAdd(data, "hasImprovement", () => entity.hasImprovement());
            TryAdd(data, "hasImprovementClass", () => entity.hasImprovementClass());
            TryAdd(data, "hasImprovementFreeSpecialist", () => entity.hasImprovementFreeSpecialist());
            TryAdd(data, "hasImprovementRural", () => entity.hasImprovementRural());
            TryAdd(data, "hasImprovementWithBorderSpread", () => entity.hasImprovementWithBorderSpread());
            TryAdd(data, "hasInactiveImprovement", () => entity.hasInactiveImprovement());
            TryAdd(data, "hasMapElementName", () => entity.hasMapElementName());
            TryAdd(data, "hasMapGeneratorData", () => entity.hasMapGeneratorData());
            TryAdd(data, "hasOwner", () => entity.hasOwner());
            TryAdd(data, "hasOwnerTribe", () => entity.hasOwnerTribe());
            TryAdd(data, "hasReligion", () => entity.hasReligion());
            TryAdd(data, "hasResource", () => entity.hasResource());
            TryAdd(data, "hasSpecialist", () => entity.hasSpecialist());
            TryAdd(data, "hasUnit", () => entity.hasUnit());
            TryAdd(data, "hasVegetation", () => entity.hasVegetation());
            TryAdd(data, "height", () => infos.height(entity.getHeight())?.mzType);
            TryAdd(data, "hiddenHeight", () => infos.height(entity.getHiddenHeight())?.mzType);
            TryAdd(data, "hiddenTerrain", () => infos.terrain(entity.getHiddenTerrain())?.mzType);
            TryAdd(data, "id", () => entity.getID());
            TryAdd(data, "improvement", () => infos.improvement(entity.getImprovement())?.mzType);
            TryAdd(data, "improvementBuildTurnsLeft", () => entity.getImprovementBuildTurnsLeft());
            TryAdd(data, "improvementBuildTurnsOriginal", () => entity.getImprovementBuildTurnsOriginal());
            TryAdd(data, "improvementClass", () => entity.getImprovementClass().ToString());
            TryAdd(data, "improvementDevelopTurns", () => entity.getImprovementDevelopTurns());
            TryAdd(data, "improvementDynamicText", () => entity.getImprovementDynamicText());
            TryAdd(data, "improvementFirstSpecialist", () => infos.specialist(entity.getImprovementFirstSpecialist())?.mzType);
            TryAdd(data, "improvementGrammaticalGender", () => entity.getImprovementGrammaticalGender().ToString());
            TryAdd(data, "improvementPillageTurns", () => entity.getImprovementPillageTurns());
            TryAdd(data, "improvementReligionPrereq", () => infos.religion(entity.getImprovementReligionPrereq())?.mzType);
            TryAdd(data, "improvementReligionSpread", () => infos.religion(entity.getImprovementReligionSpread())?.mzType);
            TryAdd(data, "improvementUnitTurns", () => entity.getImprovementUnitTurns());
            TryAdd(data, "isAnyCoastLand", () => entity.isAnyCoastLand());
            TryAdd(data, "isAnyDirty", () => entity.isAnyDirty());
            TryAdd(data, "isBorder", () => entity.isBorder());
            TryAdd(data, "isBoundary", () => entity.isBoundary());
            TryAdd(data, "isCanal", () => entity.isCanal());
            TryAdd(data, "isCitySiteAny", () => entity.isCitySiteAny());
            TryAdd(data, "isClear", () => entity.isClear());
            TryAdd(data, "isFlat", () => entity.isFlat());
            TryAdd(data, "isFreshWater", () => entity.isFreshWater());
            TryAdd(data, "isFreshWaterAccess", () => entity.isFreshWaterAccess());
            TryAdd(data, "isFreshWaterSource", () => entity.isFreshWaterSource());
            TryAdd(data, "isHarvested", () => entity.isHarvested());
            TryAdd(data, "isImprovementUnfinished", () => entity.isImprovementUnfinished());
            TryAdd(data, "isImprovementUnfinishedOrPillaged", () => entity.isImprovementUnfinishedOrPillaged());
            TryAdd(data, "isLand", () => entity.isLand());
            TryAdd(data, "isMinorCity", () => entity.isMinorCity());
            TryAdd(data, "isNationSite", () => entity.isNationSite());
            TryAdd(data, "isPassableLand", () => entity.isPassableLand());
            TryAdd(data, "isPillaged", () => entity.isPillaged());
            TryAdd(data, "isRegrowing", () => entity.isRegrowing());
            TryAdd(data, "isRiver", () => entity.isRiver());
            TryAdd(data, "isRiverE", () => entity.isRiverE());
            TryAdd(data, "isRiverNE", () => entity.isRiverNE());
            TryAdd(data, "isRiverNW", () => entity.isRiverNW());
            TryAdd(data, "isRiverSE", () => entity.isRiverSE());
            TryAdd(data, "isRiverSW", () => entity.isRiverSW());
            TryAdd(data, "isRiverW", () => entity.isRiverW());
            TryAdd(data, "isRoad", () => entity.isRoad());
            TryAdd(data, "isSaltCoastLand", () => entity.isSaltCoastLand());
            TryAdd(data, "isSaltCoastWater", () => entity.isSaltCoastWater());
            TryAdd(data, "isSaltWater", () => entity.isSaltWater());
            TryAdd(data, "isTribeSite", () => entity.isTribeSite());
            TryAdd(data, "isUrban", () => entity.isUrban());
            TryAdd(data, "isWater", () => entity.isWater());
            TryAdd(data, "landSection", () => entity.getLandSection());
            TryAdd(data, "lastTurnOwnerChange", () => entity.getLastTurnOwnerChange());
            TryAdd(data, "latitude", () => entity.getLatitude());
            TryAdd(data, "mapElementName", () => entity.getMapElementName());
            TryAdd(data, "mapElementNameType", () => entity.getMapElementNameType().ToString());
            TryAdd(data, "mapGeneratorData", () => entity.getMapGeneratorData());
            TryAdd(data, "metadata", () => entity.getMetadata());
            TryAdd(data, "movementCostExtra", () => entity.getMovementCostExtra());
            TryAdd(data, "nation", () => infos.nation(entity.getNation())?.mzType);
            TryAdd(data, "nationSite", () => infos.nation(entity.getNationSite())?.mzType);
            TryAdd(data, "numTags", () => entity.getNumTags());
            TryAdd(data, "origUrbanOwner", () => entity.getOrigUrbanOwner().ToString());
            TryAdd(data, "owner", () => entity.getOwner().ToString());
            TryAdd(data, "ownerTribe", () => infos.tribe(entity.getOwnerTribe())?.mzType);
            TryAdd(data, "regrowthTurn", () => entity.getRegrowthTurn());
            TryAdd(data, "resource", () => infos.resource(entity.getResource())?.mzType);
            TryAdd(data, "resourceHeightOffset", () => entity.getResourceHeightOffset());
            TryAdd(data, "riverSE", () => entity.getRiverSE().ToString());
            TryAdd(data, "riverSW", () => entity.getRiverSW().ToString());
            TryAdd(data, "riverW", () => entity.getRiverW().ToString());
            TryAdd(data, "specialist", () => infos.specialist(entity.getSpecialist())?.mzType);
            TryAdd(data, "specialistClass", () => entity.getSpecialistClass().ToString());
            TryAdd(data, "team", () => entity.getTeam().ToString());
            TryAdd(data, "terrain", () => infos.terrain(entity.getTerrain())?.mzType);
            TryAdd(data, "terrainStamp", () => entity.getTerrainStamp().ToString());
            TryAdd(data, "terrainStampTileID", () => entity.getTerrainStampTileID());
            TryAdd(data, "terrainUnitDamage", () => entity.getTerrainUnitDamage());
            TryAdd(data, "tradeOutpostIncome", () => entity.getTradeOutpostIncome());
            TryAdd(data, "tribeSite", () => infos.tribe(entity.getTribeSite())?.mzType);
            TryAdd(data, "vegetation", () => infos.vegetation(entity.getVegetation())?.mzType);
            TryAdd(data, "x", () => entity.getX());
            TryAdd(data, "y", () => entity.getY());

            return data;
        }

        // Parameterized getters not included in basic builder:
        // - getActiveImprovement(1 params) -> ImprovementType
        // - getAdjacentCityTerritoryCount(2 params) -> int
        // - getCitySiteSurrounded(2 params) -> CityTerritory?
        // - getClosestEdge(1 params) -> DirectionType
        // - getClosestUnit(2 params) -> Unit
        // - getConnectedCitySiteActive(1 params) -> int
        // - getConstructionAsset(2 params) -> AssetType
        // - getCornerTileOffset(1 params) -> Vector3
        // - getDirection(1 params) -> DirectionType
        // - getEdgeTileOffset(1 params) -> Vector3
        // - getFreeSpecialist(1 params) -> SpecialistType
        // - getHeightTurn(1 params) -> HeightType
        // - getImprovementCost(1 params) -> int
        // - getImprovementHeightOffset(1 params) -> float
        // - getImprovementTribeSite(1 params) -> TribeType
        // - getNextSpecialist(1 params) -> SpecialistType
        // - getOwnerColor(1 params) -> PlayerColorType
        // - getRecentAttacks(1 params) -> int
        // - getRevealedCitySite(1 params) -> CitySiteType
        // - getRevealedCityTerritory(1 params) -> int
        // ... and 106 more

        #endregion

        #region Unit Builder

        /// <summary>
        /// Build a Unit object for JSON serialization.
        /// Auto-generated from Unit.cs - 151 properties.
        /// Each property access is wrapped in try-catch for null safety.
        /// </summary>
        public static object BuildUnitObjectGenerated(Unit entity, Game game, Infos infos)
        {
            var data = new Dictionary<string, object>();

            TryAdd(data, "agentNetworkCost", () => entity.getAgentNetworkCost());
            TryAdd(data, "caravanMissionTarget", () => entity.getCaravanMissionTarget().ToString());
            TryAdd(data, "civilianCycleSubgroup", () => entity.getCivilianCycleSubgroup().ToString());
            TryAdd(data, "consumptionMercenaryModifier", () => entity.getConsumptionMercenaryModifier());
            TryAdd(data, "cooldown", () => entity.getCooldown().ToString());
            TryAdd(data, "cooldownTurns", () => entity.getCooldownTurns());
            TryAdd(data, "createTurn", () => entity.getCreateTurn());
            TryAdd(data, "currentFormation", () => entity.getCurrentFormation().ToString());
            TryAdd(data, "damage", () => entity.getDamage());
            TryAdd(data, "damagedExtraBuildTurns", () => entity.getDamagedExtraBuildTurns());
            TryAdd(data, "effectUnitCount", () => entity.getEffectUnitCount());
            TryAdd(data, "endRoutEffect", () => entity.getEndRoutEffect().ToString());
            TryAdd(data, "explorerID", () => entity.getExplorerID());
            TryAdd(data, "facing", () => entity.getFacing().ToString());
            TryAdd(data, "family", () => infos.family(entity.getFamily())?.mzType);
            TryAdd(data, "familyClass", () => entity.getFamilyClass().ToString());
            TryAdd(data, "familyOpinion", () => entity.getFamilyOpinion().ToString());
            TryAdd(data, "fatigueLimit", () => entity.getFatigueLimit());
            TryAdd(data, "formationBonus", () => entity.getFormationBonus());
            TryAdd(data, "formationTurns", () => entity.getFormationTurns());
            TryAdd(data, "fortifyBonus", () => entity.getFortifyBonus());
            TryAdd(data, "fortifyTurns", () => entity.getFortifyTurns());
            TryAdd(data, "freeActions", () => entity.getFreeActions());
            TryAdd(data, "freeActionsTaken", () => entity.getFreeActionsTaken());
            TryAdd(data, "freeImprovementBuild", () => infos.improvement(entity.getFreeImprovementBuild())?.mzType);
            TryAdd(data, "gender", () => entity.getGender().ToString());
            TryAdd(data, "generalID", () => entity.getGeneralID());
            TryAdd(data, "grammaticalGender", () => entity.getGrammaticalGender().ToString());
            TryAdd(data, "harvestDistanceModifier", () => entity.getHarvestDistanceModifier());
            TryAdd(data, "hasCaravanMissionTarget", () => entity.hasCaravanMissionTarget());
            TryAdd(data, "hasCooldown", () => entity.hasCooldown());
            TryAdd(data, "hasCriticalImmune", () => entity.hasCriticalImmune());
            TryAdd(data, "hasEffectEstablishTheology", () => entity.hasEffectEstablishTheology());
            TryAdd(data, "hasEffectMercenary", () => entity.hasEffectMercenary());
            TryAdd(data, "hasEffectSpreadReligion", () => entity.hasEffectSpreadReligion());
            TryAdd(data, "hasEffectUnitAny", () => entity.hasEffectUnitAny());
            TryAdd(data, "hasEndRoutEffect", () => entity.hasEndRoutEffect());
            TryAdd(data, "hasEnlistNext", () => entity.hasEnlistNext());
            TryAdd(data, "hasExplorer", () => entity.hasExplorer());
            TryAdd(data, "hasFamily", () => entity.hasFamily());
            TryAdd(data, "hasFamilyOpinion", () => entity.hasFamilyOpinion());
            TryAdd(data, "hasFamilyTerritoryOnly", () => entity.hasFamilyTerritoryOnly());
            TryAdd(data, "hasFreeActions", () => entity.hasFreeActions());
            TryAdd(data, "hasFreeImprovementBuild", () => entity.hasFreeImprovementBuild());
            TryAdd(data, "hasGeneral", () => entity.hasGeneral());
            TryAdd(data, "hasGeneralHopping", () => entity.hasGeneralHopping());
            TryAdd(data, "hasGeneralModifier", () => entity.hasGeneralModifier());
            TryAdd(data, "hasHarvest", () => entity.hasHarvest());
            TryAdd(data, "hasHealNeutral", () => entity.hasHealNeutral());
            TryAdd(data, "hasHealPillage", () => entity.hasHealPillage());
            TryAdd(data, "hasIgnoreZOC", () => entity.hasIgnoreZOC());
            TryAdd(data, "hasLastStand", () => entity.hasLastStand());
            TryAdd(data, "hasLaunchOffensive", () => entity.hasLaunchOffensive());
            TryAdd(data, "hasMoved", () => entity.hasMoved());
            TryAdd(data, "hasName", () => entity.hasName());
            TryAdd(data, "hasNoRoadCooldown", () => entity.hasNoRoadCooldown());
            TryAdd(data, "hasOffensiveRemoveCooldown", () => entity.hasOffensiveRemoveCooldown());
            TryAdd(data, "hasOriginalPlayer", () => entity.hasOriginalPlayer());
            TryAdd(data, "hasOriginalTribe", () => entity.hasOriginalTribe());
            TryAdd(data, "hasPillage", () => entity.hasPillage());
            TryAdd(data, "hasPlayer", () => entity.hasPlayer());
            TryAdd(data, "hasQueueList", () => entity.hasQueueList());
            TryAdd(data, "hasRebelPlayer", () => entity.hasRebelPlayer());
            TryAdd(data, "hasReligion", () => entity.hasReligion());
            TryAdd(data, "hasRemoveVegetation", () => entity.hasRemoveVegetation());
            TryAdd(data, "hasVisibleAttackCooldown", () => entity.hasVisibleAttackCooldown());
            TryAdd(data, "hasZOC", () => entity.hasZOC());
            TryAdd(data, "hp", () => entity.getHP());
            TryAdd(data, "hpMax", () => entity.getHPMax());
            TryAdd(data, "id", () => entity.getID());
            TryAdd(data, "initialGender", () => entity.getInitialGender().ToString());
            TryAdd(data, "isActiveOutOfTurn", () => entity.isActiveOutOfTurn());
            TryAdd(data, "isActivePlayer", () => entity.isActivePlayer());
            TryAdd(data, "isAlive", () => entity.isAlive());
            TryAdd(data, "isAnchored", () => entity.isAnchored());
            TryAdd(data, "isAnyDirty", () => entity.isAnyDirty());
            TryAdd(data, "isAutoHarvest", () => entity.isAutoHarvest());
            TryAdd(data, "isAutoHeal", () => entity.isAutoHeal());
            TryAdd(data, "isAutomated", () => entity.isAutomated());
            TryAdd(data, "isAutoMoveOnly", () => entity.isAutoMoveOnly());
            TryAdd(data, "isBusy", () => entity.isBusy());
            TryAdd(data, "isCapturingCity", () => entity.isCapturingCity());
            TryAdd(data, "isCriticalHit", () => entity.isCriticalHit());
            TryAdd(data, "isDamaged", () => entity.isDamaged());
            TryAdd(data, "isDead", () => entity.isDead());
            TryAdd(data, "isFatigued", () => entity.isFatigued());
            TryAdd(data, "isFormation", () => entity.isFormation());
            TryAdd(data, "isFormationMax", () => entity.isFormationMax());
            TryAdd(data, "isFortify", () => entity.isFortify());
            TryAdd(data, "isFortifyMax", () => entity.isFortifyMax());
            TryAdd(data, "isHiddenNotTemp", () => entity.isHiddenNotTemp());
            TryAdd(data, "isHuman", () => entity.isHuman());
            TryAdd(data, "isImmobile", () => entity.isImmobile());
            TryAdd(data, "isImprovingTile", () => entity.isImprovingTile());
            TryAdd(data, "isLeaderExplorer", () => entity.isLeaderExplorer());
            TryAdd(data, "isLeaderGeneral", () => entity.isLeaderGeneral());
            TryAdd(data, "isLevelMax", () => entity.isLevelMax());
            TryAdd(data, "isLevelPromotionMax", () => entity.isLevelPromotionMax());
            TryAdd(data, "isLocked", () => entity.isLocked());
            TryAdd(data, "isMarch", () => entity.isMarch());
            TryAdd(data, "isModVariables", () => entity.isModVariables());
            TryAdd(data, "isOccurrenceImpassableImmune", () => entity.isOccurrenceImpassableImmune());
            TryAdd(data, "isPass", () => entity.isPass());
            TryAdd(data, "isPromotable", () => entity.isPromotable());
            TryAdd(data, "isRaiding", () => entity.isRaiding());
            TryAdd(data, "isRemoveVegatation", () => entity.isRemoveVegatation());
            TryAdd(data, "isScout", () => entity.isScout());
            TryAdd(data, "isSentry", () => entity.isSentry());
            TryAdd(data, "isShowCriticalHit", () => entity.isShowCriticalHit());
            TryAdd(data, "isSkip", () => entity.isSkip());
            TryAdd(data, "isSleep", () => entity.isSleep());
            TryAdd(data, "isTempHidden", () => entity.isTempHidden());
            TryAdd(data, "isTribe", () => entity.isTribe());
            TryAdd(data, "isUnlimbered", () => entity.isUnlimbered());
            TryAdd(data, "isWorker", () => entity.isWorker());
            TryAdd(data, "level", () => entity.getLevel());
            TryAdd(data, "levelPromotion", () => entity.getLevelPromotion());
            TryAdd(data, "levelPromotionString", () => entity.getLevelPromotionString());
            TryAdd(data, "levelString", () => entity.getLevelString());
            TryAdd(data, "marchCost", () => entity.getMarchCost());
            TryAdd(data, "meleeCounterPercent", () => entity.getMeleeCounterPercent());
            TryAdd(data, "name", () => entity.getName());
            TryAdd(data, "nameType", () => entity.getNameType().ToString());
            TryAdd(data, "nation", () => infos.nation(entity.getNation())?.mzType);
            TryAdd(data, "nextCriticalModifier", () => entity.getNextCriticalModifier());
            TryAdd(data, "originalPlayer", () => entity.getOriginalPlayer().ToString());
            TryAdd(data, "originalTribe", () => infos.tribe(entity.getOriginalTribe())?.mzType);
            TryAdd(data, "player", () => entity.getPlayer().ToString());
            TryAdd(data, "pushEffect", () => entity.getPushEffect().ToString());
            TryAdd(data, "rebelPlayer", () => entity.getRebelPlayer().ToString());
            TryAdd(data, "rebelTeam", () => entity.getRebelTeam().ToString());
            TryAdd(data, "religion", () => infos.religion(entity.getReligion())?.mzType);
            TryAdd(data, "roadMovementModifier", () => entity.getRoadMovementModifier());
            TryAdd(data, "routChain", () => entity.getRoutChain());
            TryAdd(data, "spreadReligion", () => infos.religion(entity.getSpreadReligion())?.mzType);
            TryAdd(data, "spreadReligionTribeCost", () => entity.getSpreadReligionTribeCost());
            TryAdd(data, "stepsToFatigue", () => entity.getStepsToFatigue());
            TryAdd(data, "strengthRating", () => entity.getStrengthRating());
            TryAdd(data, "team", () => entity.getTeam().ToString());
            TryAdd(data, "tempHiddenTurns", () => entity.getTempHiddenTurns());
            TryAdd(data, "tileID", () => entity.getTileID());
            TryAdd(data, "trainCostWhole", () => entity.getTrainCostWhole());
            TryAdd(data, "trainXP", () => entity.getTrainXP());
            TryAdd(data, "tribe", () => infos.tribe(entity.getTribe())?.mzType);
            TryAdd(data, "turnsSinceLastMove", () => entity.getTurnsSinceLastMove());
            TryAdd(data, "turnSteps", () => entity.getTurnSteps());
            TryAdd(data, "type", () => infos.unit(entity.getType())?.mzType);
            TryAdd(data, "unitCycleGroup", () => entity.getUnitCycleGroup().ToString());
            TryAdd(data, "workerAnimationType", () => entity.getWorkerAnimationType().ToString());
            TryAdd(data, "xp", () => entity.getXP());
            TryAdd(data, "xpThreshold", () => entity.getXPThreshold());

            return data;
        }

        // Parameterized getters not included in basic builder:
        // - getActiveHealHP(1 params) -> int
        // - getBannerFortifyColors(2 params) -> bool
        // - getBannerMovementColors(3 params) -> bool
        // - getBuildCost(2 params) -> int
        // - getCooldownMove(2 params) -> CooldownType
        // - getCounterAttackDamage(3 params) -> int
        // - getCounterAttackDamage(4 params) -> int
        // - getDefenderRoutEffectUnit(1 params) -> EffectUnitType
        // - getEffectUnitCount(1 params) -> int
        // - getEffectUnitTurnRemaining(1 params) -> int
        // - getEventStoryTurn(1 params) -> int
        // - getHarvestYieldModifier(1 params) -> int
        // - getHireCost(2 params) -> int
        // - getIdleHealHP(1 params) -> int
        // - getImmuneEffectUnit(1 params) -> EffectUnitType
        // - getMaxOrders(1 params) -> int
        // - getMinimapColor(1 params) -> ColorType
        // - getModVariable(1 params) -> string
        // - getMovementCost(4 params) -> int
        // - getNumOrdersForCost(1 params) -> int
        // ... and 51 more

        #endregion

    }
}
