// <auto-generated>
// Generated by OldWorldCodeGen at 2026-01-30T19:12:13.6120300Z
// Do not edit manually - regenerate with: dotnet run --project tools/OldWorldCodeGen
// </auto-generated>

using System;
using System.Collections.Generic;
using TenCrowns.GameCore;

namespace OldWorldAPIEndpoint
{
    public static partial class DataBuilders
    {
        #region Character Builder

        /// <summary>
        /// Build a Character object for JSON serialization.
        /// Auto-generated from Character.cs - 183 properties.
        /// </summary>
        public static object BuildCharacterObjectGenerated(Character entity, Game game, Infos infos)
        {
            return new
            {
                abdicateTurn = entity.getAbdicateTurn(),
                age = entity.getAge(),
                ageGroup = entity.getAgeGroup().ToString(),
                ageRemainder = entity.getAgeRemainder(),
                ageTextVariable = entity.getAgeTextVariable(),
                archetype = infos.trait(entity.getArchetype())?.mzType,
                birthCityID = entity.getBirthCityID(),
                birthFatherID = entity.getBirthFatherID(),
                birthMotherID = entity.getBirthMotherID(),
                birthTurn = entity.getBirthTurn(),
                character = entity.getCharacter().ToString(),
                characterPortrait = entity.getCharacterPortrait().ToString(),
                cityAgentID = entity.getCityAgentID(),
                cityGovernorID = entity.getCityGovernorID(),
                clergyType = infos.trait(entity.getClergyType())?.mzType,
                cognomen = infos.cognomen(entity.getCognomen())?.mzType,
                council = infos.council(entity.getCouncil())?.mzType,
                courtier = entity.getCourtier().ToString(),
                customName = entity.getCustomName(),
                deadCouncil = infos.council(entity.getDeadCouncil())?.mzType,
                deathReason = entity.getDeathReason().ToString(),
                deathTurn = entity.getDeathTurn(),
                family = infos.family(entity.getFamily())?.mzType,
                familyClass = entity.getFamilyClass().ToString(),
                fatherID = entity.getFatherID(),
                firstName = entity.getFirstName(),
                firstNamePossessiveVariable = entity.getFirstNamePossessiveVariable(),
                firstNameVariable = entity.getFirstNameVariable(),
                gender = entity.getGender().ToString(),
                genderInt = entity.getGenderInt(),
                genderOpposite = entity.getGenderOpposite().ToString(),
                hasArchetype = entity.hasArchetype(),
                hasBirthCity = entity.hasBirthCity(),
                hasBirthFather = entity.hasBirthFather(),
                hasBirthMother = entity.hasBirthMother(),
                hasCharacter = entity.hasCharacter(),
                hasCognomen = entity.hasCognomen(),
                hasCustomName = entity.hasCustomName(),
                hasDeadCouncil = entity.hasDeadCouncil(),
                hasExplorerAll = entity.hasExplorerAll(),
                hasExplorerPrereq = entity.hasExplorerPrereq(),
                hasFamily = entity.hasFamily(),
                hasFather = entity.hasFather(),
                hasGeneralAll = entity.hasGeneralAll(),
                hasGeneralPrereq = entity.hasGeneralPrereq(),
                hasGovernorAll = entity.hasGovernorAll(),
                hasGovernorPrereq = entity.hasGovernorPrereq(),
                hasItems = entity.hasItems(),
                hasMother = entity.hasMother(),
                hasName = entity.hasName(),
                hasNation = entity.hasNation(),
                hasNickname = entity.hasNickname(),
                hasPlayer = entity.hasPlayer(),
                hasReligion = entity.hasReligion(),
                hasSpouseAlive = entity.hasSpouseAlive(),
                hasSpouseForeign = entity.hasSpouseForeign(),
                hasSpouseTribe = entity.hasSpouseTribe(),
                hasTitle = entity.hasTitle(),
                hasTraitDieProb = entity.hasTraitDieProb(),
                hasTraitDoomed = entity.hasTraitDoomed(),
                hasTraitFormerRegent = entity.hasTraitFormerRegent(),
                hasTraitNoBirth = entity.hasTraitNoBirth(),
                hasTraitNoCouncil = entity.hasTraitNoCouncil(),
                hasTraitNoCourtier = entity.hasTraitNoCourtier(),
                hasTraitNoEvents = entity.hasTraitNoEvents(),
                hasTraitNoExplorer = entity.hasTraitNoExplorer(),
                hasTraitNoFamilyHead = entity.hasTraitNoFamilyHead(),
                hasTraitNoGeneral = entity.hasTraitNoGeneral(),
                hasTraitNoGovernor = entity.hasTraitNoGovernor(),
                hasTraitNoJob = entity.hasTraitNoJob(),
                hasTraitNoMarry = entity.hasTraitNoMarry(),
                hasTraitNoReligion = entity.hasTraitNoReligion(),
                hasTraitNoReligionHeadNew = entity.hasTraitNoReligionHeadNew(),
                hasTraitNoSuccession = entity.hasTraitNoSuccession(),
                hasTraitRegent = entity.hasTraitRegent(),
                hasTraitSuccessionBypass = entity.hasTraitSuccessionBypass(),
                hasTraitSuccessionReturn = entity.hasTraitSuccessionReturn(),
                hasUnit = entity.hasUnit(),
                headReligion = infos.religion(entity.getHeadReligion())?.mzType,
                iD = entity.getID(),
                isAbdicated = entity.isAbdicated(),
                isActivePlayer = entity.isActivePlayer(),
                isAdult = entity.isAdult(),
                isAgeless = entity.isAgeless(),
                isAlive = entity.isAlive(),
                isAnyDirty = entity.isAnyDirty(),
                isAttractedToAny = entity.isAttractedToAny(),
                isBisexual = entity.isBisexual(),
                isCityAgent = entity.isCityAgent(),
                isCityGovernor = entity.isCityGovernor(),
                isClergy = entity.isClergy(),
                isCouncil = entity.isCouncil(),
                isCourtier = entity.isCourtier(),
                isDead = entity.isDead(),
                isFamilyHead = entity.isFamilyHead(),
                isFamilyHeadSpouse = entity.isFamilyHeadSpouse(),
                isFemale = entity.isFemale(),
                isFertileAge = entity.isFertileAge(),
                isForceInheritanceTreeInclude = entity.isForceInheritanceTreeInclude(),
                isGay = entity.isGay(),
                isHeir = entity.isHeir(),
                isHeirSpouse = entity.isHeirSpouse(),
                isHuman = entity.isHuman(),
                isInfertile = entity.isInfertile(),
                isJob = entity.isJob(),
                isLeader = entity.isLeader(),
                isLeaderAncestor = entity.isLeaderAncestor(),
                isLeaderAnySibling = entity.isLeaderAnySibling(),
                isLeaderChild = entity.isLeaderChild(),
                isLeaderDescendant = entity.isLeaderDescendant(),
                isLeaderOrChildOfLeader = entity.isLeaderOrChildOfLeader(),
                isLeaderOrDescendant = entity.isLeaderOrDescendant(),
                isLeaderOrHeir = entity.isLeaderOrHeir(),
                isLeaderOrSpouse = entity.isLeaderOrSpouse(),
                isLeaderOrSpouseOrHeir = entity.isLeaderOrSpouseOrHeir(),
                isLeaderOrSpouseOrSuccessor = entity.isLeaderOrSpouseOrSuccessor(),
                isLeaderOrSuccessor = entity.isLeaderOrSuccessor(),
                isLeaderSpouse = entity.isLeaderSpouse(),
                isMale = entity.isMale(),
                isOrWasLeader = entity.isOrWasLeader(),
                isOrWasLeaderSpouse = entity.isOrWasLeaderSpouse(),
                isOrWasRegent = entity.isOrWasRegent(),
                isRegent = entity.isRegent(),
                isReligionHead = entity.isReligionHead(),
                isRetired = entity.isRetired(),
                isRoyal = entity.isRoyal(),
                isRoyalSpouse = entity.isRoyalSpouse(),
                isSafe = entity.isSafe(),
                isSpouseLeaderDescendant = entity.isSpouseLeaderDescendant(),
                isSuccessionSkipRegent = entity.isSuccessionSkipRegent(),
                isSuccessor = entity.isSuccessor(),
                isSuccessorParent = entity.isSuccessorParent(),
                isSuccessorSpouse = entity.isSuccessorSpouse(),
                isTemporary = entity.isTemporary(),
                isTribe = entity.isTribe(),
                isTribeLeader = entity.isTribeLeader(),
                isUnitExplorer = entity.isUnitExplorer(),
                isUnitGeneral = entity.isUnitGeneral(),
                isValidChooseName = entity.isValidChooseName(),
                job = infos.job(entity.getJob())?.mzType,
                leaderIndex = entity.getLeaderIndex(),
                leaderTurn = entity.getLeaderTurn(),
                legitimacy = entity.getLegitimacy(),
                level = entity.getLevel(),
                makeAgentExtraOpinion = entity.getMakeAgentExtraOpinion(),
                makeExplorerExtraOpinion = entity.getMakeExplorerExtraOpinion(),
                makeGeneralExtraOpinion = entity.getMakeGeneralExtraOpinion(),
                makeGovernorExtraOpinion = entity.getMakeGovernorExtraOpinion(),
                maxStrengths = entity.getMaxStrengths(),
                maxWeaknesses = entity.getMaxWeaknesses(),
                motherID = entity.getMotherID(),
                nameType = entity.getNameType().ToString(),
                nation = infos.nation(entity.getNation())?.mzType,
                nationTurn = entity.getNationTurn(),
                nickname = entity.getNickname().ToString(),
                nicknameText = entity.getNicknameText(),
                numChildren = entity.getNumChildren(),
                numEventStoryTexts = entity.getNumEventStoryTexts(),
                numEventStoryTurns = entity.getNumEventStoryTurns(),
                numSpouses = entity.getNumSpouses(),
                player = entity.getPlayer().ToString(),
                playerInt = entity.getPlayerInt(),
                playerOpinionOfCharacterReligion = entity.getPlayerOpinionOfCharacterReligion().ToString(),
                ratingAttackModifierTotal = entity.getRatingAttackModifierTotal(),
                ratingCriticalChanceTotal = entity.getRatingCriticalChanceTotal(),
                ratingHarvestModifierTotal = entity.getRatingHarvestModifierTotal(),
                ratingUnitXPTotal = entity.getRatingUnitXPTotal(),
                regentTurn = entity.getRegentTurn(),
                religion = infos.religion(entity.getReligion())?.mzType,
                safeTurn = entity.getSafeTurn(),
                suffix = entity.getSuffix(),
                team = entity.getTeam().ToString(),
                title = entity.getTitle().ToString(),
                traitBirthModifier = entity.getTraitBirthModifier(),
                traitNickname = entity.getTraitNickname().ToString(),
                traitTitle = entity.getTraitTitle().ToString(),
                tribe = infos.tribe(entity.getTribe())?.mzType,
                unitBuildModifier = entity.getUnitBuildModifier(),
                unitID = entity.getUnitID(),
                upgradeXPThreshold = entity.getUpgradeXPThreshold(),
                wasFamilyHead = infos.family(entity.getWasFamilyHead())?.mzType,
                wasReligionHead = infos.religion(entity.getWasReligionHead())?.mzType,
                xP = entity.getXP()
            };
        }

        // Parameterized getters not included in basic builder:
        // - getAgeGroupOnTurn(1 params) -> CharacterAgeGroupType
        // - getAgeOnTurn(1 params) -> int
        // - getAncestorLevel(2 params) -> int
        // - getChangeJobExtraOpinion(1 params) -> int
        // - getCharacterRelation(1 params) -> RelativeType
        // - getCognomenMinValue(1 params) -> int
        // - getEventStoryText(1 params) -> CharacterStoryData
        // - getEventStoryTurn(1 params) -> int
        // - getFamilyOpinionCouncil(1 params) -> int
        // - getFirstName(1 params) -> StringBuilder
        // - getFullName(11 params) -> string
        // - getFullName(12 params) -> StringBuilder
        // - getFullNameExtraVariable(6 params) -> TextVariable
        // - getFullNameVariable(12 params) -> TextVariable
        // - getJobOpinion(1 params) -> int
        // - getLegitimacy(2 params) -> int
        // - getMakeCouncilExtraOpinion(1 params) -> int
        // - getNameVariable(7 params) -> TextVariable
        // - getNationEthnicity(1 params) -> int
        // - getOpinion(1 params) -> OpinionCharacterType
        // ... and 67 more

        #endregion

        #region City Builder

        /// <summary>
        /// Build a City object for JSON serialization.
        /// Auto-generated from City.cs - 126 properties.
        /// </summary>
        public static object BuildCityObjectGenerated(City entity, Game game, Infos infos)
        {
            return new
            {
                activeImprovementClassCountAll = entity.getActiveImprovementClassCountAll(),
                activeImprovementCountAll = entity.getActiveImprovementCountAll(),
                adjacentClassCostModifier = entity.getAdjacentClassCostModifier(),
                assimilateTurns = entity.getAssimilateTurns(),
                buildCount = entity.getBuildCount(),
                buildTurnChange = entity.getBuildTurnChange(),
                buildUnitFamily = infos.family(entity.getBuildUnitFamily())?.mzType,
                buyTileCount = entity.getBuyTileCount(),
                capturePlayer = entity.getCapturePlayer().ToString(),
                captureTeam = entity.getCaptureTeam().ToString(),
                captureThreshold = entity.getCaptureThreshold(),
                captureTribe = infos.tribe(entity.getCaptureTribe())?.mzType,
                captureTurns = entity.getCaptureTurns(),
                citizens = entity.getCitizens(),
                citizensPlusQueuedWithNoProgress = entity.getCitizensPlusQueuedWithNoProgress(),
                citizensQueue = entity.getCitizensQueue(),
                citizensTotal = entity.getCitizensTotal(),
                citySite = entity.getCitySite(),
                completedBuild = entity.getCompletedBuild(),
                culture = infos.culture(entity.getCulture())?.mzType,
                cultureStep = entity.getCultureStep(),
                currentBuild = entity.getCurrentBuild(),
                currentBuildType = entity.getCurrentBuildType().ToString(),
                damage = entity.getDamage(),
                defaultGovernorID = entity.getDefaultGovernorID(),
                family = infos.family(entity.getFamily())?.mzType,
                familyClass = entity.getFamilyClass().ToString(),
                familyOpinion = entity.getFamilyOpinion().ToString(),
                firstPlayer = entity.getFirstPlayer().ToString(),
                firstTeam = entity.getFirstTeam().ToString(),
                foundedTurn = entity.getFoundedTurn(),
                giftedTurn = entity.getGiftedTurn(),
                governorID = entity.getGovernorID(),
                grammaticalGender = entity.getGrammaticalGender().ToString(),
                growthCount = entity.getGrowthCount(),
                happinessLevel = entity.getHappinessLevel(),
                hasAnyAgentCharacter = entity.hasAnyAgentCharacter(),
                hasAutobuildQueued = entity.hasAutobuildQueued(),
                hasBuild = entity.hasBuild(),
                hasBuildAnyReligionUnitUnlock = entity.hasBuildAnyReligionUnitUnlock(),
                hasBuildPlanned = entity.hasBuildPlanned(),
                hasCapturePlayer = entity.hasCapturePlayer(),
                hasCaptureTribe = entity.hasCaptureTribe(),
                hasCompletedBuild = entity.hasCompletedBuild(),
                hasDefaultGovernor = entity.hasDefaultGovernor(),
                hasFamily = entity.hasFamily(),
                hasFamilyOpinion = entity.hasFamilyOpinion(),
                hasGovernor = entity.hasGovernor(),
                hasLastPlayer = entity.hasLastPlayer(),
                hasLastTribe = entity.hasLastTribe(),
                hasNation = entity.hasNation(),
                hasPlayer = entity.hasPlayer(),
                hasRebelEffects = entity.hasRebelEffects(),
                hasStateReligion = entity.hasStateReligion(),
                healExtra = entity.getHealExtra(),
                hP = entity.getHP(),
                hPMax = entity.getHPMax(),
                hPMaxExtra = entity.getHPMaxExtra(),
                hurryCivicsCost = entity.getHurryCivicsCost(),
                hurryCivicsCount = entity.getHurryCivicsCount(),
                hurryDiscontent = entity.getHurryDiscontent(),
                hurryDiscontentModifier = entity.getHurryDiscontentModifier(),
                hurryMoneyCost = entity.getHurryMoneyCost(),
                hurryMoneyCount = entity.getHurryMoneyCount(),
                hurryOrdersCost = entity.getHurryOrdersCost(),
                hurryOrdersCount = entity.getHurryOrdersCount(),
                hurryPopulationCost = entity.getHurryPopulationCost(),
                hurryPopulationCount = entity.getHurryPopulationCount(),
                hurryTrainingCost = entity.getHurryTrainingCost(),
                hurryTrainingCount = entity.getHurryTrainingCount(),
                iD = entity.getID(),
                improvementCostModifier = entity.getImprovementCostModifier(),
                isActivePlayer = entity.isActivePlayer(),
                isAnyDirty = entity.isAnyDirty(),
                isAutomated = entity.isAutomated(),
                isBuildNoHurry = entity.isBuildNoHurry(),
                isCapital = entity.isCapital(),
                isCapturedCapital = entity.isCapturedCapital(),
                isConnected = entity.isConnected(),
                isDamaged = entity.isDamaged(),
                isDefaultGovernorRuling = entity.isDefaultGovernorRuling(),
                isFamilySeat = entity.isFamilySeat(),
                isGoverned = entity.isGoverned(),
                isGovernorLeader = entity.isGovernorLeader(),
                isHuman = entity.isHuman(),
                isIdle = entity.isIdle(),
                isReligionHolyCityAny = entity.isReligionHolyCityAny(),
                isTribe = entity.isTribe(),
                isUnitCapturingCity = entity.isUnitCapturingCity(),
                isVulnerable = entity.isVulnerable(),
                isYieldRateDefendingAny = entity.isYieldRateDefendingAny(),
                lastPlayer = entity.getLastPlayer().ToString(),
                lastTeam = entity.getLastTeam().ToString(),
                lastTribe = infos.tribe(entity.getLastTribe())?.mzType,
                luxuryCount = entity.getLuxuryCount(),
                militaryUnitCount = entity.getMilitaryUnitCount(),
                name = entity.getName(),
                nameType = entity.getNameType().ToString(),
                nation = infos.nation(entity.getNation())?.mzType,
                numRandomPromotions = entity.getNumRandomPromotions(),
                paganReligionCount = entity.getPaganReligionCount(),
                passiveHealDamage = entity.getPassiveHealDamage(),
                player = entity.getPlayer().ToString(),
                playerInt = entity.getPlayerInt(),
                population = entity.getPopulation(),
                projectCostModifier = entity.getProjectCostModifier(),
                raidedTurn = entity.getRaidedTurn(),
                rangeChange = entity.getRangeChange(),
                regrowthModifier = entity.getRegrowthModifier(),
                religionCount = entity.getReligionCount(),
                religionNonStateCount = entity.getReligionNonStateCount(),
                saltWaterTiles = entity.getSaltWaterTiles(),
                specialistCostModifier = entity.getSpecialistCostModifier(),
                specialistCount = entity.getSpecialistCount(),
                specialistProducedCount = entity.getSpecialistProducedCount(),
                specialistRuralTrainTimeModifier = entity.getSpecialistRuralTrainTimeModifier(),
                specialistUrbanCostModifier = entity.getSpecialistUrbanCostModifier(),
                specialistUrbanTrainTimeModifier = entity.getSpecialistUrbanTrainTimeModifier(),
                strengthModifier = entity.getStrengthModifier(),
                team = entity.getTeam().ToString(),
                tileID = entity.getTileID(),
                tradeNetwork = entity.getTradeNetwork(),
                tribe = infos.tribe(entity.getTribe())?.mzType,
                urbanBuildTurnChange = entity.getUrbanBuildTurnChange(),
                urbanSpecialistCount = entity.getUrbanSpecialistCount(),
                urbanTiles = entity.getUrbanTiles()
            };
        }

        // Parameterized getters not included in basic builder:
        // - getActiveImprovementClassCount(1 params) -> int
        // - getActiveImprovementCount(1 params) -> int
        // - getAddProjectYieldRate(3 params) -> int
        // - getAddResourceTiles(3 params) -> bool
        // - getAgentCharacterID(1 params) -> int
        // - getAgentTeamPlayer(1 params) -> PlayerType
        // - getAssimilateYieldModifier(1 params) -> int
        // - getBaseYieldNet(1 params) -> int
        // - getBaseYieldNetForGovernor(3 params) -> int
        // - getBestSpecialistNoPrereq(1 params) -> SpecialistType
        // - getBorderPattern(1 params) -> BorderPatternType
        // - getBuildDiff(2 params) -> int
        // - getBuildDiffWholePositive(2 params) -> int
        // - getBuildProgress(2 params) -> int
        // - getBuildQueueNode(1 params) -> CityQueueData
        // - getBuildRate(2 params) -> int
        // - getBuildThreshold(1 params) -> int
        // - getBuildThresholdWhole(1 params) -> int
        // - getBuildTurnsLeft(1 params) -> int
        // - getBuildUnitLevels(1 params) -> int
        // ... and 124 more

        #endregion

        #region Player Builder

        /// <summary>
        /// Build a Player object for JSON serialization.
        /// Auto-generated from Player.cs - 122 properties.
        /// </summary>
        public static object BuildPlayerObjectGenerated(Player entity, Game game, Infos infos)
        {
            return new
            {
                aIAutoPlayToTurn = entity.getAIAutoPlayToTurn(),
                borderVisibility = entity.getBorderVisibility(),
                buyTileCount = entity.getBuyTileCount(),
                capitalCityID = entity.getCapitalCityID(),
                chosenHeirID = entity.getChosenHeirID(),
                consumptionModifier = entity.getConsumptionModifier(),
                convertOrdersCost = entity.getConvertOrdersCost(),
                convertOrdersYield = infos.yield(entity.getConvertOrdersYield())?.mzType,
                crest = entity.getCrest().ToString(),
                customName = entity.getCustomName(),
                customReminder = entity.getCustomReminder(),
                development = entity.getDevelopment().ToString(),
                difficulty = entity.getDifficulty().ToString(),
                difficultyMode = entity.getDifficultyMode().ToString(),
                dynasty = entity.getDynasty().ToString(),
                familySupremacy = infos.family(entity.getFamilySupremacy())?.mzType,
                firstPopup = entity.getFirstPopup(),
                fixedNumCities = entity.getFixedNumCities(),
                founderID = entity.getFounderID(),
                harvestModifier = entity.getHarvestModifier(),
                hasAchievementLocked = entity.hasAchievementLocked(),
                hasAchievementUnlocked = entity.hasAchievementUnlocked(),
                hasAutomatedUnits = entity.hasAutomatedUnits(),
                hasCapitalCity = entity.hasCapitalCity(),
                hasChosenHeir = entity.hasChosenHeir(),
                hasCustomName = entity.hasCustomName(),
                hasDecisions = entity.hasDecisions(),
                hasDynasty = entity.hasDynasty(),
                hasFounder = entity.hasFounder(),
                hasHeir = entity.hasHeir(),
                hasLeader = entity.hasLeader(),
                hasLeaderFamily = entity.hasLeaderFamily(),
                hasLeaderSpouseAlive = entity.hasLeaderSpouseAlive(),
                hasNation = entity.hasNation(),
                hasScenarioCompleted = entity.hasScenarioCompleted(),
                hasStateReligion = entity.hasStateReligion(),
                hasTurnSummary = entity.hasTurnSummary(),
                isActive = entity.isActive(),
                isAIAutoPlay = entity.isAIAutoPlay(),
                isAlive = entity.isAlive(),
                isAnyDirty = entity.isAnyDirty(),
                isAnyPickLater = entity.isAnyPickLater(),
                isAnyTechAvailable = entity.isAnyTechAvailable(),
                isCityMaxReached = entity.isCityMaxReached(),
                isCompletedGameSaved = entity.isCompletedGameSaved(),
                isConvertedLegitimacy = entity.isConvertedLegitimacy(),
                isDead = entity.isDead(),
                isFirstTurnProcessing = entity.isFirstTurnProcessing(),
                isFounded = entity.isFounded(),
                isHuman = entity.isHuman(),
                isHumanOriginal = entity.isHumanOriginal(),
                isInitialized = entity.isInitialized(),
                isLeaderAlive = entity.isLeaderAlive(),
                isPlaying = entity.isPlaying(),
                isProcessingTurn = entity.isProcessingTurn(),
                isProcessingTurnStart = entity.isProcessingTurnStart(),
                isResearching = entity.isResearching(),
                isStartCityNumberFlexible = entity.isStartCityNumberFlexible(),
                isSurrendered = entity.isSurrendered(),
                isTeamHuman = entity.isTeamHuman(),
                isTechRedraw = entity.isTechRedraw(),
                isTurnEnded = entity.isTurnEnded(),
                isTurnSummaryReady = entity.isTurnSummaryReady(),
                isTutorial = entity.isTutorial(),
                isUsedOffensive = entity.isUsedOffensive(),
                isVersionMismatch = entity.isVersionMismatch(),
                language = entity.getLanguage().ToString(),
                lastDoTurn = entity.getLastDoTurn(),
                leaderFamily = infos.family(entity.getLeaderFamily())?.mzType,
                legitimacy = entity.getLegitimacy(),
                minStartingCities = entity.getMinStartingCities(),
                missionModifier = entity.getMissionModifier(),
                money = entity.getMoney(),
                moneyWhole = entity.getMoneyWhole(),
                nation = infos.nation(entity.getNation())?.mzType,
                numCities = entity.getNumCities(),
                numDecisions = entity.getNumDecisions(),
                numEmptySites = entity.getNumEmptySites(),
                numFamilies = entity.getNumFamilies(),
                numGameLoads = entity.getNumGameLoads(),
                numGoals = entity.getNumGoals(),
                numMemories = entity.getNumMemories(),
                numMissions = entity.getNumMissions(),
                numPopups = entity.getNumPopups(),
                numStartingTiles = entity.getNumStartingTiles(),
                numTiles = entity.getNumTiles(),
                numTrades = entity.getNumTrades(),
                numTributes = entity.getNumTributes(),
                numUnits = entity.getNumUnits(),
                onlineID = entity.getOnlineID(),
                ordersLeft = entity.getOrdersLeft(),
                originalCapitalCityID = entity.getOriginalCapitalCityID(),
                player = entity.getPlayer().ToString(),
                playerEmail = entity.getPlayerEmail(),
                playerInt = entity.getPlayerInt(),
                popupTechDiscovered = infos.tech(entity.getPopupTechDiscovered())?.mzType,
                recruitLegitimacy = entity.getRecruitLegitimacy(),
                reloads = entity.getReloads(),
                saltWaterTileCount = entity.getSaltWaterTileCount(),
                sellPenaltyModifier = entity.getSellPenaltyModifier(),
                startingTileID = entity.getStartingTileID(),
                startTurnCities = entity.getStartTurnCities(),
                stateReligion = infos.religion(entity.getStateReligion())?.mzType,
                stateReligionChangeCount = entity.getStateReligionChangeCount(),
                stateReligionSpreadChange = entity.getStateReligionSpreadChange(),
                successionCount = entity.getSuccessionCount(),
                successionGender = entity.getSuccessionGender().ToString(),
                successionOrder = entity.getSuccessionOrder().ToString(),
                team = entity.getTeam().ToString(),
                techCostModifier = entity.getTechCostModifier(),
                techResearching = infos.tech(entity.getTechResearching())?.mzType,
                techsAvailableChange = entity.getTechsAvailableChange(),
                timeStockpile = entity.getTimeStockpile(),
                trainingOrderModifier = entity.getTrainingOrderModifier(),
                tribeFatigueLimitChange = entity.getTribeFatigueLimitChange(),
                tribeMercenaryCount = entity.getTribeMercenaryCount(),
                turnTimeNeeded = entity.getTurnTimeNeeded(),
                visionChange = entity.getVisionChange(),
                wonderModifier = entity.getWonderModifier(),
                worldReligionCount = entity.getWorldReligionCount(),
                worldReligionSpreadChange = entity.getWorldReligionSpreadChange(),
                yieldUpkeepModifier = entity.getYieldUpkeepModifier()
            };
        }

        // Parameterized getters not included in basic builder:
        // - getActiveImprovementClassCount(1 params) -> int
        // - getActiveImprovementCount(1 params) -> int
        // - getActiveLaw(1 params) -> LawType
        // - getAddUrbanCost(2 params) -> int
        // - getAdoptReligionCost(1 params) -> int
        // - getAmbitionDecisions(1 params) -> int
        // - getBonesTime(1 params) -> int
        // - getBonusCount(1 params) -> int
        // - getBorderColor(1 params) -> ColorType
        // - getBorderPattern(1 params) -> BorderPatternType
        // - getBuyImprovementCost(4 params) -> int
        // - getBuyYieldsCost(1 params) -> int
        // - getBuyYieldsCost(1 params) -> int
        // - getCharacterMission(1 params) -> MissionData
        // - getConnectedForeignYieldPer(3 params) -> int
        // - getConnectedForeignYieldTotal(3 params) -> int
        // - getCouncilCharacter(1 params) -> int
        // - getCouncilYieldRateCharacterCity(3 params) -> int
        // - getCurrentTurnLogText(2 params) -> StringBuilder
        // - getDecisionAt(1 params) -> DecisionData
        // ... and 175 more

        #endregion

        #region Tile Builder

        /// <summary>
        /// Build a Tile object for JSON serialization.
        /// Auto-generated from Tile.cs - 117 properties.
        /// </summary>
        public static object BuildTileObjectGenerated(Tile entity, Game game, Infos infos)
        {
            return new
            {
                activeImprovementClass = entity.getActiveImprovementClass().ToString(),
                area = entity.getArea(),
                areaTileCount = entity.getAreaTileCount(),
                cityID = entity.getCityID(),
                citySite = entity.getCitySite().ToString(),
                cityTerritory = entity.getCityTerritory(),
                constructionProgress = entity.getConstructionProgress(),
                currentSpecialist = infos.specialist(entity.getCurrentSpecialist())?.mzType,
                customMapElementName = entity.getCustomMapElementName(),
                extraBlockingVisibilityHeight = entity.getExtraBlockingVisibilityHeight(),
                family = infos.family(entity.getFamily())?.mzType,
                harvestTurn = entity.getHarvestTurn(),
                hasCanDamageUnit = entity.hasCanDamageUnit(),
                hasCity = entity.hasCity(),
                hasCityTerritory = entity.hasCityTerritory(),
                hasFamily = entity.hasFamily(),
                hasFreeSpecialist = entity.hasFreeSpecialist(),
                hasGovernor = entity.hasGovernor(),
                hasImprovement = entity.hasImprovement(),
                hasImprovementClass = entity.hasImprovementClass(),
                hasImprovementFreeSpecialist = entity.hasImprovementFreeSpecialist(),
                hasImprovementRural = entity.hasImprovementRural(),
                hasImprovementWithBorderSpread = entity.hasImprovementWithBorderSpread(),
                hasInactiveImprovement = entity.hasInactiveImprovement(),
                hasMapElementName = entity.hasMapElementName(),
                hasMapGeneratorData = entity.hasMapGeneratorData(),
                hasOwner = entity.hasOwner(),
                hasOwnerTribe = entity.hasOwnerTribe(),
                hasReligion = entity.hasReligion(),
                hasResource = entity.hasResource(),
                hasSpecialist = entity.hasSpecialist(),
                hasUnit = entity.hasUnit(),
                hasVegetation = entity.hasVegetation(),
                height = infos.height(entity.getHeight())?.mzType,
                hiddenHeight = infos.height(entity.getHiddenHeight())?.mzType,
                hiddenTerrain = infos.terrain(entity.getHiddenTerrain())?.mzType,
                iD = entity.getID(),
                improvement = infos.improvement(entity.getImprovement())?.mzType,
                improvementBuildTurnsLeft = entity.getImprovementBuildTurnsLeft(),
                improvementBuildTurnsOriginal = entity.getImprovementBuildTurnsOriginal(),
                improvementClass = entity.getImprovementClass().ToString(),
                improvementDevelopTurns = entity.getImprovementDevelopTurns(),
                improvementDynamicText = entity.getImprovementDynamicText(),
                improvementFirstSpecialist = infos.specialist(entity.getImprovementFirstSpecialist())?.mzType,
                improvementGrammaticalGender = entity.getImprovementGrammaticalGender().ToString(),
                improvementPillageTurns = entity.getImprovementPillageTurns(),
                improvementReligionPrereq = infos.religion(entity.getImprovementReligionPrereq())?.mzType,
                improvementReligionSpread = infos.religion(entity.getImprovementReligionSpread())?.mzType,
                improvementUnitTurns = entity.getImprovementUnitTurns(),
                isAnyCoastLand = entity.isAnyCoastLand(),
                isAnyDirty = entity.isAnyDirty(),
                isBorder = entity.isBorder(),
                isBoundary = entity.isBoundary(),
                isCanal = entity.isCanal(),
                isCitySiteAny = entity.isCitySiteAny(),
                isClear = entity.isClear(),
                isFlat = entity.isFlat(),
                isFreshWater = entity.isFreshWater(),
                isFreshWaterAccess = entity.isFreshWaterAccess(),
                isFreshWaterSource = entity.isFreshWaterSource(),
                isHarvested = entity.isHarvested(),
                isImprovementUnfinished = entity.isImprovementUnfinished(),
                isImprovementUnfinishedOrPillaged = entity.isImprovementUnfinishedOrPillaged(),
                isLand = entity.isLand(),
                isMinorCity = entity.isMinorCity(),
                isNationSite = entity.isNationSite(),
                isPassableLand = entity.isPassableLand(),
                isPillaged = entity.isPillaged(),
                isRegrowing = entity.isRegrowing(),
                isRiver = entity.isRiver(),
                isRiverE = entity.isRiverE(),
                isRiverNE = entity.isRiverNE(),
                isRiverNW = entity.isRiverNW(),
                isRiverSE = entity.isRiverSE(),
                isRiverSW = entity.isRiverSW(),
                isRiverW = entity.isRiverW(),
                isRoad = entity.isRoad(),
                isSaltCoastLand = entity.isSaltCoastLand(),
                isSaltCoastWater = entity.isSaltCoastWater(),
                isSaltWater = entity.isSaltWater(),
                isTribeSite = entity.isTribeSite(),
                isUrban = entity.isUrban(),
                isWater = entity.isWater(),
                landSection = entity.getLandSection(),
                lastTurnOwnerChange = entity.getLastTurnOwnerChange(),
                latitude = entity.getLatitude(),
                mapElementName = entity.getMapElementName(),
                mapElementNameType = entity.getMapElementNameType().ToString(),
                mapGeneratorData = entity.getMapGeneratorData(),
                metadata = entity.getMetadata(),
                movementCostExtra = entity.getMovementCostExtra(),
                nation = infos.nation(entity.getNation())?.mzType,
                nationSite = infos.nation(entity.getNationSite())?.mzType,
                numTags = entity.getNumTags(),
                origUrbanOwner = entity.getOrigUrbanOwner().ToString(),
                owner = entity.getOwner().ToString(),
                ownerTribe = infos.tribe(entity.getOwnerTribe())?.mzType,
                regrowthTurn = entity.getRegrowthTurn(),
                resource = infos.resource(entity.getResource())?.mzType,
                resourceHeightOffset = entity.getResourceHeightOffset(),
                riverSE = entity.getRiverSE().ToString(),
                riverSW = entity.getRiverSW().ToString(),
                riverW = entity.getRiverW().ToString(),
                specialist = infos.specialist(entity.getSpecialist())?.mzType,
                specialistClass = entity.getSpecialistClass().ToString(),
                team = entity.getTeam().ToString(),
                terrain = infos.terrain(entity.getTerrain())?.mzType,
                terrainStamp = entity.getTerrainStamp().ToString(),
                terrainStampTileID = entity.getTerrainStampTileID(),
                terrainUnitDamage = entity.getTerrainUnitDamage(),
                tradeOutpostIncome = entity.getTradeOutpostIncome(),
                tribeSite = infos.tribe(entity.getTribeSite())?.mzType,
                vegetation = infos.vegetation(entity.getVegetation())?.mzType,
                worldPosition = entity.getWorldPosition(),
                worldPosition3D = entity.getWorldPosition3D(),
                x = entity.getX(),
                y = entity.getY()
            };
        }

        // Parameterized getters not included in basic builder:
        // - getActiveImprovement(1 params) -> ImprovementType
        // - getAdjacentCityTerritoryCount(2 params) -> int
        // - getCitySiteSurrounded(2 params) -> CityTerritory?
        // - getClosestEdge(1 params) -> DirectionType
        // - getClosestUnit(2 params) -> Unit
        // - getConnectedCitySiteActive(1 params) -> int
        // - getConstructionAsset(2 params) -> AssetType
        // - getCornerTileOffset(1 params) -> Vector3
        // - getDirection(1 params) -> DirectionType
        // - getEdgeTileOffset(1 params) -> Vector3
        // - getFreeSpecialist(1 params) -> SpecialistType
        // - getHeightTurn(1 params) -> HeightType
        // - getImprovementCost(1 params) -> int
        // - getImprovementHeightOffset(1 params) -> float
        // - getImprovementTribeSite(1 params) -> TribeType
        // - getNextSpecialist(1 params) -> SpecialistType
        // - getOwnerColor(1 params) -> PlayerColorType
        // - getRecentAttacks(1 params) -> int
        // - getRevealedCitySite(1 params) -> CitySiteType
        // - getRevealedCityTerritory(1 params) -> int
        // ... and 106 more

        #endregion

        #region Unit Builder

        /// <summary>
        /// Build a Unit object for JSON serialization.
        /// Auto-generated from Unit.cs - 152 properties.
        /// </summary>
        public static object BuildUnitObjectGenerated(Unit entity, Game game, Infos infos)
        {
            return new
            {
                agentNetworkCost = entity.getAgentNetworkCost(),
                caravanMissionTarget = entity.getCaravanMissionTarget().ToString(),
                civilianCycleSubgroup = entity.getCivilianCycleSubgroup().ToString(),
                consumptionMercenaryModifier = entity.getConsumptionMercenaryModifier(),
                cooldown = entity.getCooldown().ToString(),
                cooldownTurns = entity.getCooldownTurns(),
                createTurn = entity.getCreateTurn(),
                currentFormation = entity.getCurrentFormation().ToString(),
                damage = entity.getDamage(),
                damagedExtraBuildTurns = entity.getDamagedExtraBuildTurns(),
                effectUnitCount = entity.getEffectUnitCount(),
                endRoutEffect = entity.getEndRoutEffect().ToString(),
                explorerID = entity.getExplorerID(),
                facing = entity.getFacing().ToString(),
                family = infos.family(entity.getFamily())?.mzType,
                familyClass = entity.getFamilyClass().ToString(),
                familyOpinion = entity.getFamilyOpinion().ToString(),
                fatigueLimit = entity.getFatigueLimit(),
                formationBonus = entity.getFormationBonus(),
                formationTurns = entity.getFormationTurns(),
                fortifyBonus = entity.getFortifyBonus(),
                fortifyTurns = entity.getFortifyTurns(),
                freeActions = entity.getFreeActions(),
                freeActionsTaken = entity.getFreeActionsTaken(),
                freeImprovementBuild = infos.improvement(entity.getFreeImprovementBuild())?.mzType,
                gender = entity.getGender().ToString(),
                generalID = entity.getGeneralID(),
                grammaticalGender = entity.getGrammaticalGender().ToString(),
                harvestDistanceModifier = entity.getHarvestDistanceModifier(),
                hasCaravanMissionTarget = entity.hasCaravanMissionTarget(),
                hasCooldown = entity.hasCooldown(),
                hasCriticalImmune = entity.hasCriticalImmune(),
                hasEffectEstablishTheology = entity.hasEffectEstablishTheology(),
                hasEffectMercenary = entity.hasEffectMercenary(),
                hasEffectSpreadReligion = entity.hasEffectSpreadReligion(),
                hasEffectUnitAny = entity.hasEffectUnitAny(),
                hasEndRoutEffect = entity.hasEndRoutEffect(),
                hasEnlistNext = entity.hasEnlistNext(),
                hasExplorer = entity.hasExplorer(),
                hasFamily = entity.hasFamily(),
                hasFamilyOpinion = entity.hasFamilyOpinion(),
                hasFamilyTerritoryOnly = entity.hasFamilyTerritoryOnly(),
                hasFreeActions = entity.hasFreeActions(),
                hasFreeImprovementBuild = entity.hasFreeImprovementBuild(),
                hasGeneral = entity.hasGeneral(),
                hasGeneralHopping = entity.hasGeneralHopping(),
                hasGeneralModifier = entity.hasGeneralModifier(),
                hasHarvest = entity.hasHarvest(),
                hasHealNeutral = entity.hasHealNeutral(),
                hasHealPillage = entity.hasHealPillage(),
                hasIgnoreZOC = entity.hasIgnoreZOC(),
                hasLastStand = entity.hasLastStand(),
                hasLaunchOffensive = entity.hasLaunchOffensive(),
                hasMoved = entity.hasMoved(),
                hasName = entity.hasName(),
                hasNoRoadCooldown = entity.hasNoRoadCooldown(),
                hasOffensiveRemoveCooldown = entity.hasOffensiveRemoveCooldown(),
                hasOriginalPlayer = entity.hasOriginalPlayer(),
                hasOriginalTribe = entity.hasOriginalTribe(),
                hasPillage = entity.hasPillage(),
                hasPlayer = entity.hasPlayer(),
                hasQueueList = entity.hasQueueList(),
                hasRebelPlayer = entity.hasRebelPlayer(),
                hasReligion = entity.hasReligion(),
                hasRemoveVegetation = entity.hasRemoveVegetation(),
                hasVisibleAttackCooldown = entity.hasVisibleAttackCooldown(),
                hasZOC = entity.hasZOC(),
                hP = entity.getHP(),
                hPMax = entity.getHPMax(),
                iD = entity.getID(),
                initialGender = entity.getInitialGender().ToString(),
                isActiveOutOfTurn = entity.isActiveOutOfTurn(),
                isActivePlayer = entity.isActivePlayer(),
                isAlive = entity.isAlive(),
                isAnchored = entity.isAnchored(),
                isAnyDirty = entity.isAnyDirty(),
                isAutoHarvest = entity.isAutoHarvest(),
                isAutoHeal = entity.isAutoHeal(),
                isAutomated = entity.isAutomated(),
                isAutoMoveOnly = entity.isAutoMoveOnly(),
                isBusy = entity.isBusy(),
                isCapturingCity = entity.isCapturingCity(),
                isCriticalHit = entity.isCriticalHit(),
                isDamaged = entity.isDamaged(),
                isDead = entity.isDead(),
                isFatigued = entity.isFatigued(),
                isFormation = entity.isFormation(),
                isFormationMax = entity.isFormationMax(),
                isFortify = entity.isFortify(),
                isFortifyMax = entity.isFortifyMax(),
                isHiddenNotTemp = entity.isHiddenNotTemp(),
                isHuman = entity.isHuman(),
                isImmobile = entity.isImmobile(),
                isImprovingTile = entity.isImprovingTile(),
                isLeaderExplorer = entity.isLeaderExplorer(),
                isLeaderGeneral = entity.isLeaderGeneral(),
                isLevelMax = entity.isLevelMax(),
                isLevelPromotionMax = entity.isLevelPromotionMax(),
                isLocked = entity.isLocked(),
                isMarch = entity.isMarch(),
                isModVariables = entity.isModVariables(),
                isOccurrenceImpassableImmune = entity.isOccurrenceImpassableImmune(),
                isPass = entity.isPass(),
                isPromotable = entity.isPromotable(),
                isRaiding = entity.isRaiding(),
                isRemoveVegatation = entity.isRemoveVegatation(),
                isScout = entity.isScout(),
                isSentry = entity.isSentry(),
                isShowCriticalHit = entity.isShowCriticalHit(),
                isSkip = entity.isSkip(),
                isSleep = entity.isSleep(),
                isTempHidden = entity.isTempHidden(),
                isTribe = entity.isTribe(),
                isUnlimbered = entity.isUnlimbered(),
                isWorker = entity.isWorker(),
                level = entity.getLevel(),
                levelPromotion = entity.getLevelPromotion(),
                levelPromotionString = entity.getLevelPromotionString(),
                levelString = entity.getLevelString(),
                marchCost = entity.getMarchCost(),
                meleeCounterPercent = entity.getMeleeCounterPercent(),
                name = entity.getName(),
                nameType = entity.getNameType().ToString(),
                nation = infos.nation(entity.getNation())?.mzType,
                nextCriticalModifier = entity.getNextCriticalModifier(),
                originalPlayer = entity.getOriginalPlayer().ToString(),
                originalTribe = infos.tribe(entity.getOriginalTribe())?.mzType,
                player = entity.getPlayer().ToString(),
                pushEffect = entity.getPushEffect().ToString(),
                queuedTile = entity.getQueuedTile(),
                rebelPlayer = entity.getRebelPlayer().ToString(),
                rebelTeam = entity.getRebelTeam().ToString(),
                religion = infos.religion(entity.getReligion())?.mzType,
                roadMovementModifier = entity.getRoadMovementModifier(),
                routChain = entity.getRoutChain(),
                spreadReligion = infos.religion(entity.getSpreadReligion())?.mzType,
                spreadReligionTribeCost = entity.getSpreadReligionTribeCost(),
                stepsToFatigue = entity.getStepsToFatigue(),
                strengthRating = entity.getStrengthRating(),
                team = entity.getTeam().ToString(),
                tempHiddenTurns = entity.getTempHiddenTurns(),
                tileID = entity.getTileID(),
                trainCostWhole = entity.getTrainCostWhole(),
                trainXP = entity.getTrainXP(),
                tribe = infos.tribe(entity.getTribe())?.mzType,
                turnsSinceLastMove = entity.getTurnsSinceLastMove(),
                turnSteps = entity.getTurnSteps(),
                type = infos.unit(entity.getType())?.mzType,
                unitCycleGroup = entity.getUnitCycleGroup().ToString(),
                workerAnimationType = entity.getWorkerAnimationType().ToString(),
                xP = entity.getXP(),
                xPThreshold = entity.getXPThreshold()
            };
        }

        // Parameterized getters not included in basic builder:
        // - getActiveHealHP(1 params) -> int
        // - getBannerFortifyColors(2 params) -> bool
        // - getBannerMovementColors(3 params) -> bool
        // - getBuildCost(2 params) -> int
        // - getCooldownMove(2 params) -> CooldownType
        // - getCounterAttackDamage(3 params) -> int
        // - getCounterAttackDamage(4 params) -> int
        // - getDefenderRoutEffectUnit(1 params) -> EffectUnitType
        // - getEffectUnitCount(1 params) -> int
        // - getEffectUnitTurnRemaining(1 params) -> int
        // - getEventStoryTurn(1 params) -> int
        // - getHarvestYieldModifier(1 params) -> int
        // - getHireCost(2 params) -> int
        // - getIdleHealHP(1 params) -> int
        // - getImmuneEffectUnit(1 params) -> EffectUnitType
        // - getMaxOrders(1 params) -> int
        // - getMinimapColor(1 params) -> ColorType
        // - getModVariable(1 params) -> string
        // - getMovementCost(4 params) -> int
        // - getNumOrdersForCost(1 params) -> int
        // ... and 51 more

        #endregion

    }
}
